- timescaledb/how-to-guides/ingest-data.md
Some URLs in this page were declared, but missing from the list at the bottom of the page. This adds the missing ones, and fixes some syntax.
> Missing URLs

- timescaledb/overview/release-notes/index.md
This is a second attempt at the release notes for 2.2.1. There were issues in the original attempt that were difficult to overcome through a rebase and this was a faster route.
> Release note changes for 2.2.1

- timescaledb/how-to-guides/hypertables/create.md
The link to https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/ from the https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/#create-a-hypertable page was broken. This updates the broken link. Also fixes some other general issues with syntax on this page.
Report from community: https://timescaledb.slack.com/archives/C4GT3N90X/p1620696533186300
> fix broken link

- timescaledb/how-to-guides/replication-and-ha/index.md
- timescaledb/how-to-guides/replication-and-ha/replication.md
Fixes the empty landing page for Replication & HA. Also, as a drive-by edit, pulls out the double spaces after periods.
Fixes https://github.com/timescale/docs/issues/33
> Fix replication index page.

- timescale-forge/scaling-a-service.md
Updated storage limit from 4TB to 10TB.
> Updated with larger storage numbers.

- timescaledb/how-to-guides/install-timescaledb/installation-apt-debian.md
- timescaledb/how-to-guides/install-timescaledb/installation-apt-ubuntu.md
- timescaledb/how-to-guides/install-timescaledb/installation-source-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-source.md
- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-yum.md
- timescaledb/how-to-guides/install-timescaledb/timescale-forge.md
The `:pg_version:` entity was not being replaced in the Installation docs. After discussion with @tedsczelecki we decided to hard code it. I've gone with 13, as it's the latest version, LMK if it should be 12.
Fixes: https://github.com/timescale/docs/issues/31
> Remove pg_version entity and replace with version.

- timescaledb/how-to-guides/continuous-aggregates/manually-refresh-specific-ranges.md
Link was written, but no URL provided. This PR adds a URL, and removes the unnecessary admon markup.
Community report: https://timescaledb.slack.com/archives/C4GT3N90X/p1620772714211200
> Add missing link, and remove admon markup

- timescaledb/how-to-guides/migrate-data/different-db.md
- timescaledb/how-to-guides/migrate-data/import-csv.md
- timescaledb/how-to-guides/migrate-data/index.md
- timescaledb/how-to-guides/migrate-data/same-db.md
- timescaledb/how-to-guides/page-index/page-index.js
Broken anchor tags in this doc. Decided to split the docs into the different methods rather than just fix the tags.
Fixes https://github.com/timescale/docs/issues/50
> Split page into different methods

- timescaledb/how-to-guides/multi-node-setup/index.md
Community member noted that multi-scale on forge was listed as 'coming soon', but it's available now! Updated the text appropriately.
https://timescaledb.slack.com/archives/C4GT3N90X/p1621381914043200?thread_ts=1621381914.043200&cid=C4GT3N90X
> Remove coming soon note, and update surrounding text

- timescale-forge/create-a-service.md
This admon was not displaying markup correctly. This PR rewords slightly, and uses backticks for the menu name. Also adds in a missing period.
> Reword admon and fix markup

- timescale-forge/create-a-service.md
Updated compute numbers to 32CPU / 128GB RAM for the "create service" docs.
> Updated Forge compute numbers

- api/chunks.md
The timescaledb_information.chunks view used to return NULL in the is_compressed field for distributed chunks. This changes the view to always return true or false, depending on the chunk status flags in the Access Node. This is a hint and cannot be used as a source of truth for the compression state of the actual chunks in the Data Nodes.
https://github.com/timescale/timescaledb/pull/3220
> Update is_compressed column in chunks view

- .github/ISSUE_TEMPLATE/bug_report.md
Removes URL to private repo from template.
> Remove URL from template

- timescaledb/overview/release-notes/index.md
Fixes: https://github.com/timescale/docs/issues/70
> First draft on TSDB 2.3 and PG 11 deprecation.

- timescaledb/tutorials/analyze-cryptocurrency-data.md
Just a small fix in the TIME as we up case only the SQL commands.
https://docs.timescale.com/timescaledb/latest/tutorials/analyze-cryptocurrency-data/
> Fix TIME to time as it refers to the column

- timescaledb/how-to-guides/continuous-aggregates/adding-automatic-refresh-policies.md
- timescaledb/how-to-guides/continuous-aggregates/best-practices.md
- timescaledb/how-to-guides/continuous-aggregates/drop-raw-data.md
This PR fixes a few broken links in the caggs how-to pages.
> Fixes for a few broken links in the Continuous Aggregations How-To

- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
Fix Windows installer URL to point to PostgreSQL 13 instead of 12.
Fixes https://github.com/timescale/timescaledb/issues/3276
> Fix Windows installer URL

- .github/workflows/deploy.yml
- timescaledb/how-to-guides/page-index/page-index.js
- timescaledb/how-to-guides/update-timescaledb/index.md
- timescaledb/how-to-guides/update-timescaledb/update-timescaledb-2.md
- timescaledb/how-to-guides/update-timescaledb/update-timescaledb.md
- timescaledb/how-to-guides/update-timescaledb/updating-docker.md
It's become evident that we never created a page for upgrading within the 2.x line. In reality, upgrading 1.x->1.x or 2.x->2.x is the same. We created the "upgrade from 1.x to 2.x" document when that was the only new thing. But once a major version is installed, we keep things stable for updated until the next major version release.
This PR creates that new generic page and fixes some links to the older "1.x" docs to keep everything contained on the new site.
> Adding in generic update instructions and fixing some links.

- timescaledb/how-to-guides/install-timescaledb/installation-apt-debian.md
- timescaledb/how-to-guides/install-timescaledb/installation-apt-ubuntu.md
- timescaledb/how-to-guides/install-timescaledb/installation-homebrew.md
- timescaledb/how-to-guides/install-timescaledb/installation-source-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-source.md
- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-yum.md
- timescaledb/how-to-guides/update-timescaledb/index.md
- timescaledb/how-to-guides/update-timescaledb/update-timescaledb-2.md
Removes reference to pg11 pre-req in all install pages, and updates to pg 12 or 13.
Fixes https://github.com/timescale/docs/issues/103
> Update pg version in all Install pages.

- api/compression.md
Add missing limitations when inserting into compressed chunks.
Fixes #timescale/timescaledb/issues/3323
> Support inserting into compressed chunks

- timescaledb/how-to-guides/compression/manually-compress-chunks.md
The tables on this page were broken. This PR corrects the md so that the tables show correctly. Checked and all other tables have rendered OK.
- [ x Latest (Default)
> Add whitespace around tables

- timescaledb/tutorials/grafana/setup-alerts.md
This fixes some broken links in the Grafana tutorial.
Fixes https://github.com/timescale/docs/issues/126
Fixes https://github.com/timescale/docs/issues/125
> Fix broken links in Grafana tutorial

- timescaledb/tutorials/visualize-with-tableu.md
This fixes some broken links in the Tableau tutorial.
Fixes https://github.com/timescale/docs/issues/127
Fixes https://github.com/timescale/docs/issues/128
> Fix broken links in Tableau tutorial

- timescaledb/how-to-guides/update-timescaledb/index.md
- timescaledb/how-to-guides/update-timescaledb/update-timescaledb-2.md
During the initial PR of these changes I inadvertently removed PG11 compatibility for TimescaleDB 2.1-2.3. This has caused confusion with some recent users.
> Pg11 compatibility fix

- timescaledb/how-to-guides/install-timescaledb/installation-ubuntu-ami.md
The links in the two admonitions at the bottom of the page were not correctly formed, and the second link pointed to an our of date page on the amazon site. Also removes two unused links from the reference block.
> Fix broken links in AMI install page

- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
The download link for Windows points to a version that was not the most recent one.
Also, even though PostgreSQL 12 is supported, there was no download link shown.
This PR updates the version and shows links for PG 12 and 13.
> Update Windows link to 2.3.0 and show both PG 12 and 13

- timescaledb/overview/index.md
Saw that the Overview page was out of date and refreshed it to match the contents of www/products and link to Youtube.
> New Overview page for TimescaleDB

- timescaledb/how-to-guides/continuous-aggregates/index.md
Adding refreshing policies on the autocomplete is redirecting to [this](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/adding-automatic-refresh-policies/) page that is broken as the content page changed to not say `adding-automatic` in the URL: https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/refresh-policies/
[Add Refresh Policies] is also broken trying from [this link](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/#continuous-aggregates).
Fixes #181.
> Fix #181 broken link reference

- timescaledb/getting-started/compress-data.md
Alias missing at the end of the sql statement. Found the inconsistency helping a user in the [community](https://timescaledb.slack.com/archives/C4GT3N90X/p1626175697283500).
I confirmed that all other statements are right.
<details>
<summary> ~/c/t/docs on fix-sql-query ◦ ag -B 3 -A 2 "SELECT (de)?compress_chunk\(i\)"  </summary>
```
timescaledb/getting-started/compress-data.md
67----------------------------------------------------
68--- Manual compression
69----------------------------------------------------
70:SELECT compress_chunk(i)
71-FROM show_chunks('weather_metrics', older_than => INTERVAL ' 10 years') i;
72-```
timescaledb/how-to-guides/compression/decompress-chunks.md
30-To decompress a set of chunks based on a time range, you can use the output of
31-`show_chunks` to …
> Fix SQL missing alias

- api/page-index/page-index.js
- timescale-cloud/page-index/page-index.js
- timescaledb/how-to-guides/page-index/page-index.js
- timescaledb/tutorials/analyze-cryptocurrency-data.md
- timescaledb/tutorials/index.md
- timescaledb/tutorials/monitor-django-with-prometheus.md
- timescaledb/tutorials/monitor-timescale-cloud-with-prometheus.md
- timescaledb/tutorials/nyc-taxi-cab.md
- timescaledb/tutorials/page-index/page-index.js
- timescaledb/tutorials/setting-up-timescale-cloud-endpoint-for-prometheus.md
- timescaledb/tutorials/simulate-iot-sensor-data.md
- timescaledb/tutorials/time-series-forecast.md
Several elements of the left nav were inconsistently named. Also, the tutorials section didn't have a proper order. Cleaned up both for consistency.
Fixes: https://github.com/timescale/docs/issues/166
> Cleaned up left nav entries and tutorials pages for consistency

- timescale-forge/customize-configuration.md
While the FDW extension might be installed, it's not yet enabled as the platform does not yet expose inter-service connections for security reasons.
**N/A ?**
> Remove Postgres FDW, as remote connections not yet enabled

- api/experimental.md
- api/page-index/page-index.js
- api/time_bucket_ng.md
This PR adds the documentation to the new experimental schema and the experimental `time_bucket_ng()` function.
Nope 🤷‍♂️
> Docs for timescaledb_experimental.time_bucket_ng()

- timescaledb/how-to-guides/continuous-aggregates/materialized-hypertables.md
- timescaledb/how-to-guides/data-tiering/move-data.md
Fixes a couple of small typos reported in two pages.
- Fixes https://github.com/timescale/docs/issues/209
- Fixes https://github.com/timescale/docs/issues/208
> Fix small typos

- timescaledb/overview/release-notes/index.md
> TimescaleDB 2.4 Release notes

- api/mean.md
- api/percentile_agg.md
- api/time_bucket_ng.md
- timescaledb/getting-started/next-steps.md
- timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
- timescaledb/overview/faq/faq-products.md
- timescaledb/overview/index.md
- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
- timescaledb/quick-start/ruby.md
- timescaledb/tutorials/analyze-cryptocurrency-data.md
- timescaledb/tutorials/grafana/setup-alerts.md
After fixing some web-documentation issues, we re-ran MOZ. Many of the errors will be mitigated by a separate update to the redirect links (https://github.com/timescale/web-documentation/pull/202), but there are still valid errors in these documentation files. There will be a few more once we let all of this run it's course one more time, but these seem to be the most egregious right now.
Aiming to get below 10 4xx errors that we have control over by late next week. ;-) 
> Ryanb 404 fixes

- timescale-forge/backup-restore-cloud.md
- timescale-forge/page-index/page-index.js
Adds page about backups in ~Forge~ Cloud
Fixes https://github.com/timescale/docs/issues/121
> Add page about backups

- api/copy_chunk_experimental.md
- api/move_chunk_experimental.md
- api/page-index/page-index.js
- api/time_bucket_ng.md
Move experimental features out of the 'experimental' directory, to their correct locations. Add the `experimental` tag (https://github.com/timescale/web-documentation/pull/220) and admonitions.
> Move experimental features

- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
The Windows download links were outdated, this PR updates them to 2.4.1
Partial https://github.com/timescale/docs/issues/316
> Update Windows download links to 2.4.1

- api/time_bucket_ng.md
Just some general tidy up.
Related to: https://github.com/timescale/docs/pull/308
> Small line edits to time_bucket_ng API

- timescaledb/how-to-guides/install-timescaledb/installation-apt-debian.md
Adds the command to install the timescaledb-tools package before using timescaledb-tune.
Fixes https://github.com/timescale/docs/issues/317
> Add command to install timescaledb-tools

- timescaledb/how-to-guides/multi-node-setup/required-configuration.md
Remove 'repeatable' isolation level from multinode docs
Fixes https://github.com/timescale/docs/issues/329
> Small edit to multinode docs

- timescaledb/how-to-guides/install-timescaledb/installation-apt-ubuntu.md
Updates install instructions to avoid deprecated apt-key command.
Fixes https://github.com/timescale/docs/issues/350
> Update install instructions

- timescaledb/tutorials/nfl-analytics/index.md
- timescaledb/tutorials/nfl-analytics/ingest-and-query.md
The NFL tutorial did not include toolkit as a pre-req. This includes it in the index, and adds an admonition at the start of the queries section.
- Fixes https://github.com/timescale/timescaledb/issues/3513
- Fixes https://github.com/timescale/docs/issues/347
> Add the toolkit as a pre-req to the tutorial.

- api/time_bucket_ng.md
This PR documents the differences between time_bucket() and time_bucket_ng(). They are important because initially we assumed that time_bucket_ng() will be 100% backward compatible with time_bucket().
None.
> Document the differences between time_bucket() and time_bucket_ng()

- api/time_bucket_ng.md
Document the fact that time_bucket_ng() supports time zones.
Fixes https://github.com/timescale/timescaledb-private/issues/956
> time_bucket_ng() - document time zones support

- api/time_bucket.md
The documentation claims that the argument name of time_bucket() is `time` while in fact, it's name is `ts`.
None
> Fix the argument name in time_bucket() documentation

- api/time_bucket_ng.md
This PR adds the documentation of required and optional arguments of time_bucket_ng().
None.
> Document the required and optional arguments of time_bucket_ng()

- timescaledb/how-to-guides/continuous-aggregates/about-continuous-aggregates.md
- timescaledb/how-to-guides/continuous-aggregates/create-a-continuous-aggregate.md
- timescaledb/how-to-guides/continuous-aggregates/troubleshooting.md
Reworded the relevant sections to make it clear that window functions are not supported.
Fixes https://github.com/timescale/docs/issues/154
> Make sure window functions are listed as unsupported

- timescaledb/how-to-guides/schema-management/json.md
Fix typo (double _are_) in [JSON support for semi-structured data](https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/json/#indexing-json-fields).
Fixes #440
> Fix typo in JSON docs

- promscale/index.md
- promscale/install-promscale.md
Add link to Promscale developer docs on GitHub
Fixes https://github.com/timescale/docs/issues/389
> Add link to developer docs on GH

- timescaledb/how-to-guides/continuous-aggregates/about-continuous-aggregates.md
- timescaledb/how-to-guides/continuous-aggregates/troubleshooting.md
Moves limitations under its own heading, and adds `JOIN` as explicitly unsupported. Updates caggs tshooting section to include `JOIN` as unsupported, and adds a new section to troubleshoot lcof and NULL values.
- Fixes https://github.com/timescale/timescaledb/issues/1466
- Fixes https://github.com/timescale/docs/issues/415
> Emphasise unsupported, and add lcof tshooting

- timescaledb/how-to-guides/replication-and-ha/replication.md
Updates link to Postgres docs to use the most recent docs, instead of a specific version.
Fixes https://github.com/timescale/docs/issues/454
> Change URL to point to current pg docs

- api/_template.md
Our API docs are pretty inconsistent. This PR adds an API doc template at `api/_template.md` to help contributors stay consistent when they are writing new API docs.
Thanks to @gayyappan for the idea!
> Adds an (unlinked) API template

- cloud/cloud-multi-node.md
- cloud/create-a-service.md
- cloud/customize-configuration.md
- cloud/disk-management.md
- cloud/maintenance.md
- cloud/scaling-a-service.md
- cloud/vpc-peering-aws/create.md
This updates the screenshots for all pages under the Timescale Cloud section: https://docs.timescale.com/cloud/latest/
Please click through the pages on the preview to make sure all images are rendering OK
> Update screenshots for new branding - Timescale Cloud section

- api/create_distributed_hypertable.md
- api/percentile-aggregation-methods.md
- cloud/vpc-peering-aws/migrate.md
- mst/create-a-service.md
- mst/metrics-datadog.md
- mst/user-management.md
- mst/viewing-service-logs.md
- timescaledb/how-to-guides/install-timescaledb/installation-mst.md
- timescaledb/how-to-guides/install-timescaledb/managed-service-for-timescaledb.md
- timescaledb/tutorials/grafana/installation.md
Update grafana install docs from cloud -> mst and change old cloud portal links
- [x ] Latest (Default)
https://github.com/timescale/docs/issues/500
> update grafana install doc and change old cloud login links

- api/cleanup_copy_chunk_operation_experimental.md
- api/copy_chunk_experimental.md
- api/move_chunk_experimental.md
- api/page-index/page-index.js
- timescaledb/how-to-guides/multi-node-setup/required-configuration.md
* Add `cleanup_copy_chunk_operation` to the API docs. This function
deals with cleaning up failed copy or move operations.
* Add a note about required `wal_level` to the experimental API
documentation for `copy_chunk` and `move_chunk`.
* Add references across the different sections for easier navigation.
> Improve documentation for copy/move chunk

- timescaledb/how-to-guides/connecting/psql.md
Homebrew on Apple Silicon uses a new path for the prefix /opt/homebrew/bin whereas Intel installations still utilize /usr/local/bin.
N/A
> Reference new path of Homebrew prefix

- api/create_distributed_restore_point.md
- api/page-index/page-index.js
The docs for this API call got lost in the restructure somehow
Originally added in https://github.com/timescale/docs.timescale.com-content/pull/673
> Add missing API doc for create_distributed_restore_point

- timescaledb/overview/core-concepts/hypertables-and-chunks.md
Fixing a typo to use an adjective where there used to (incorrectly) be an adverb
> Fix typo 'primarily' > 'primary'

- api/time_bucket_ng.md
For readers is better show SQL statements highlighting its syntax.
Seems it was missed when introduced the `time_bucket_ng` documentation
like other documentation sections already does.
> Syntax highlight for SQL statements

- timescaledb/how-to-guides/multinode-timescaledb/about-multinode.md
The old docs had a section that briefly described the consistency
model of multi-node, including how transactions work with 2PC.
Add the missing section to the "about multi-node" section.
> Add missing section on multi-node consistency model

- api/time_bucket_ng.md
Several users expected that since time_bucket_ng() supports months and timezones, this functionality is also supported in CAGGs. It's not clear from the documentation that it's not true. The proposed patch clarifies what is currently supported on the CAGGs side.
https://github.com/timescale/timescaledb/issues/414#issuecomment-954480123
Also, Slack.
> Clarify what functionality of time_bucket_ng() is supported by CAGGs

- timescaledb/how-to-guides/install-timescaledb/installation-ubuntu-ami.md
- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
Updated AMI ids for timescaledb 2.5.1 release.
> Adjust AMI ids for TimescaleDB 2.5.1

- api/create_distributed_hypertable.md
- api/create_hypertable.md
- timescaledb/how-to-guides/hypertables/best-practices.md
There are references to the old default time interval (from `v0.11.0`) which don't apply anymore
> Remove old default interval references

- timescaledb/how-to-guides/update-timescaledb/index.md
> Fix typo in update-timescaledb how to guide

- cloud/maintenance.md
Clarify content around downtime for maintenance windows. Fix bad heading.
Fixes https://github.com/timescale/docs-private/issues/15
Fixes https://github.com/timescale/docs/issues/647
> Update wording around downtime. Fix heading.

- api/time_bucket_ng.md
- State that monthly buckets in CAGGs are going to be available since 2.6.0
- Explicitly state that CAGG that uses an experimental function should be dropped and replaced in the feature
This PR adds the documentation for https://github.com/timescale/timescaledb/pull/3753
> Update time_bucket_ng() docs for the upcoming 2.6.0 release

- api/add_compression_policy.md
- api/alter_materialized_view.md
- api/continuous_aggregates.md
- api/remove_compression_policy.md
- timescaledb/how-to-guides/continuous-aggregates/compression-on-continuous-aggregates.md
- timescaledb/how-to-guides/continuous-aggregates/index.md
- timescaledb/how-to-guides/continuous-aggregates/troubleshooting.md
This is a doc PR to describe a new feature : compression on continuous aggregates
#Links
https://docs.google.com/document/d/1iUm5Q4pWqbTRLoYzpM4fo-dBFa7lbfVZcmc5sRSG83U/edit?usp=sharing
https://github.com/timescale/product/issues/54
> Doc updates for compression  on continuous aggregate feature

- install/installation-windows.md
Reported by community member Stefan (thank you) there was a 'g' missing in the path to the bin folder. This PR addresses the issue.
To fix the typo in a path (which can be inconvenient). 
- [ x] Latest (Default)
N/A
> Typo in path fixed

- install/installation-debian.md
While individual packages in the apt repository are not signed the package list still is though. So we need to install our GPG key for package list verification. This PR adds this missing command and also adds lsb-release,  apt-transport-https and wget to the list of packages to install cause they are used in the instructions but might not be installed by default on some installations.
Fixes #715
> Fix apt installation instructions

- install/installation-macos.md
Removes some duplicated copy from a warning in the macOS Homebrew install docs.
> Fix typo in macOS Homebrew install docs

- promscale/installation/source.md
Add link to GH releases page so the user knows how to get the url to the binary file
> Add link to GH releases page

- timescaledb/getting-started/create-hypertable.md
When reaching the end of [this page](https://docs.timescale.com/timescaledb/latest/getting-started/create-hypertable/#learn-more-about-hypertables-and-chunks), the user is left with an empty table. We have the instructions in the getting started to populate the table with sample data. We should add the link to those instructions.
Adding a link to the sample dataset to help users in their learning process.
N/A
> Adding a link to the sample dataset

- install/installation-cloud-image.md
- install/installation-debian.md
- install/installation-macos.md
- install/installation-redhat.md
- install/installation-source.md
- install/installation-windows.md
- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
> Fix mistyped TimescaleDB name

- promscale/installation/source.md
Add parameters for host and database which are needed for folks that don't run Promscale and. the database on the same host (the majority).
> Fix Promscale command

- timescaledb/how-to-guides/continuous-aggregates/materialized-hypertables.md
In an example, use the fully qualified name of the materialization hypertable, because it doesn't work otherwise.
Fixes https://github.com/timescale/timescaledb/issues/4002
> Use a fully qualified hypertable name in an example

- api/chunk_compression_stats.md
Clarify when chunk_compression_stats view is updated
2.x all versions (from the introduction of chunk_compression_stats view).
Addresses:  https://github.com/timescale/timescaledb/issues/3982
> Clarify when chunk_compression_stats is updated.

- timescaledb/how-to-guides/configuration/postgres-config.md
Fix misspell in signal word on postgres-config.md page
> Fix misspell on postgres-config.md page

- timescaledb/quick-start/node.md
npx command was incorrect.
Fixes https://github.com/timescale/docs/issues/731
> Fix command error in Node code quick start

- api/time_bucket_ng.md
Update the documentation accordingly.
None
> Update the docs for CAGGs with TZ support

- timescaledb/overview/data-model-flexibility/index.md
Ending of page is a bit abrupt since the "next page" button isn't immediately obvious
> Add links to data model index page

- timescaledb/quick-start/index.md
"Quickstarts" as a term appears to be used in the industry, but we specifically use "quick start" several other places. For consistency, recommending this space.
@jproman1 request
> add space between quick and starts

- CONTRIBUTING.md
Fixed the 404 link for docs-standards
> [Update] Fixed the 404 link for docs-standards

- install/installation-debian.md
Add step to apt install instructions to add the Timescale GPG key.
Fixes https://github.com/timescale/docs/issues/705
> Add step to add GPG key for apt install.

- mst/user-management.md
Some of the nuance on the user management page was lost in the transition from the Kbase. This clarifies what is meant by 'manage services' by changing the column heading, and including a note.
- Fixes https://github.com/timescale/docs/issues/711
- Original PR with the content migration from Kbase: https://github.com/timescale/docs/pull/225
> Change phrasing on 'manage services' to make the meaning clearer

- install/installation-cloud.md
Fixes the page not found error for install-psql in the "Connect to your service from the command prompt" section of Install Timescale Cloud page
> [update] Install Timescale Cloud

- install/installation-windows.md
Fix 404 on configuration link.
> fix windows-install configuration link

- timescaledb/tutorials/index.md
Make spelling of "dataset" consistent across pages
Fixes #777
> Make dataset one word for consistency across docs

- timescaledb/overview/core-concepts/backup-restore.md
Remove a warning that says that multi-node doesn't support a
consistent restore point. This hasn't been true for some time since we
have `create_distributed_restore_point`.
- [ x] Latest (Default)
> Remove warning about backups on multi-node

- api/time_bucket_ng.md
Added clarification that timezone param is required for buckets that are less than a day. Also fixed the formatting of the first table.
Fixes https://github.com/timescale/docs/issues/792
> Add note about timezone required for buckets less than one day + edits

- cloud/page-index/page-index.js
"Scale a service" appears twice in the Cloud nav, linking to the same page each time. This PR removes one of them.
> Remove redundant nav item in Cloud section

- timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
pg_restore with -j option does not work for timescaledb extension
All
- [x ] Latest (Default)
any older version of the docs that we still maintain.
This is an old problem that has not been documented.
Fixes https://github.com/timescale/timescaledb/issues/4101
> Update  pg_restore limitations

- install/installation-ubuntu-ami.md
Turn off Vale Google.Units rule for Ubuntu AMI table because the image IDs somehow trigger the unit rule (which is configured to error level and so blocks merging when Vale picks it up in other PRs)
> Turn off Vale Google.Units rule for Ubuntu AMI table

- api/time_bucket_ng.md
Docs for https://github.com/timescale/timescaledb/pull/4045
> Update time_bucket_ng() docs; custom origin support will be available since 2.7.0

- cloud/maintenance.md
Add instructions to the Cloud Maintenance section about major PG upgrades.
Fixes https://github.com/timescale/docs-private/issues/20
> Add postgres upgrade info to maint section

- promscale/installation/kubernetes.md
- promscale/tobs/about.md
As I was going through the promscale & friends installation process I've noticed a few links and paths were broken.
> Fix for broken links and paths in promscale docs.

- timescaledb/how-to-guides/continuous-aggregates/compression-on-continuous-aggregates.md
- timescaledb/how-to-guides/page-index/page-index.js
With the 2.6 release, the page for compressing continuous aggregates was missed. This adds the page back in and fixes content.
- [ x] Latest (Default)
> Adding missng page for compressing continuous aggregates

- cloud/customize-configuration.md
Added clarification that Timescale Cloud does not support multiple databases within a single service.  
> Multiple databases

- timescaledb/how-to-guides/hypertables/alter.md
- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
- timescaledb/how-to-guides/multinode-timescaledb/about-multinode.md
- timescaledb/how-to-guides/multinode-timescaledb/index.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-administration.md
- timescaledb/how-to-guides/page-index/page-index.js
Add a section on multi-node administrations. This includes:
* A description of multi-node-specific limitations for administration
* Role management
* Database administration
Co-authored-by: Lana Brindley <github@lanabrindley.com>
This change targets the 2.6.0 release and was previously reverted from an earlier docs release.
> Add multi-node administration section

- api/duration_in.md
- api/freq_agg.md
- api/frequency-analysis.md
- api/topn.md
- api/values-freq_agg.md
I recently some new documents for some experimental toolkit features.
It looks like the links in these documents were not properly set up.
> Fixing broken links in new toolkit docs

- cloud/migrate-to-cloud/entire-database.md
- cloud/migrate-to-cloud/schema-then-data.md
- timescaledb/how-to-guides/migrate-data/different-db.md
- Fix outdated link in cloud migration docs
- Edit instructions for migrating from different database and add link to new cloud migration guide so readers can find more detailed instructions
> Update migration docs

- .vscode/api-reference.code-snippets
- .vscode/highlight-blank.code-snippets
- api/_template.md
Minor edits to API template
- Add syntax example right after the introductory sentence for quick reference (this is the pattern we currently have on many of the hyperfunctions docs)
- Put callouts before "for more information" (not terribly tied to this if anyone disagrees)
Add/edit VS code snippets
- Add an API snippet for quickly inserting the template
- Edit existing highlight snippet to enumerate options for highlight type
- Add a new highlight snippet to insert a blank snippet (existing snippet converts selected text to highlight)
> Edit templates and add VS Code snippets

- timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
TimescaleDB toolkit is now available as an Ubuntu, Debian, or RPM package. This PR adds package installation instructions to the Toolkit install guide.
Also includes:
- Minor fixes to align with branding and style guide
- Spell out reference links so Vale can check for broken links
Fixes #541
> Add instructions for installing Toolkit from package

- cloud/operations.md
- Correct Operations/Password section to clarify that it resets the service password, not the Cloud password
- Add mention that you can change from SCRAM to MD5 authentication
Fixes #866
> Edit reset service password section

- timescaledb/tutorials/telegraf-output-plugin.md
Adds deprecation notice
Fixes https://github.com/timescale/docs/issues/873
> Add deprecation notice for telegraf plugin

- timescaledb/quick-start/ruby.md
Added a note about configuring environment so that the tests don't fail.
- [*] Latest (Default)
[#752](https://github.com/timescale/docs/issues/752)
> [Update] Quick Start: Ruby and TimescaleDB

- promscale/distributed-tracing.md
- promscale/installation/docker.md
- promscale/installation/index.md
- promscale/installation/tobs.md
- promscale/send-data/opentelemetry.md
Removed the beta information in the Promscale documents for the tracing-GA release.
Fixes #[921] (https://github.com/timescale/docs/issues/921)
> [Update] ABL - removed beta information

- api/frequency-analysis.md
The Frequency Analysis page under API Reference->Hyperfunctions contained a broken link and hadn't been updated with all of the new methods included in toolkit 1.6.0.
> Updating Frequency Analysis page to reflect toolkit 1.6.0

- cloud/high-availability.md
Changing the early access description to be more in line with the [blog](https://www.timescale.com/blog/high-availability-for-your-production-environments-introducing-database-replication-in-timescale-cloud/)
The early access description isn't quite accurate. It's more about new features coming to this feature, rather than stability.
> Update early access description

- promscale/installation/tobs.md
Quick fix to problem with short url returning 403 when the user agent is set to "curl/....".
> Quick fix to problem with short url returning 403

- api/add_dimension.md
- timescaledb/how-to-guides/user-defined-actions/example-generic-retention.md
The available columns in TimescaleDB are:
View "timescaledb_information.hypertables"
Column        |   Type   | Collation | Nullable | Default
---------------------+----------+-----------+----------+---------
hypertable_schema   | name     |           |          |
hypertable_name     | name     |           |          |
owner               | name     |           |          |
num_dimensions      | smallint |           |          |
num_chunks          | bigint   |           |          |
compression_enabled | boolean  |           |          |
is_distributed      | boolean  |           |          |
replication_factor  | smallint |           |          |
data_nodes          | name[]   |           |          |
tablespaces         | name[]   |           |          |
Which documentation version …
> Update the column names

- install/installation-docker.md
- timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
- Add a tip to use timescaledb image for ARM64 deployments.
- Point to timescaledb-ha image.
> Toolkit: Document installation via Docker.

- install/installation-docker.md
Update Docker installation to point to timescaledb-ha image.
> Update Docker installation to point to timescaledb-ha image.

- install/installation-debian.md
In the debian install documentation the instruction to add the timescale
GPG key was duplicated, once before adding the repository, and once
after. This doesn't cause any issues, but is unnecessary.
> Remove duplicate "add GPG key" instruction

- install/installation-debian.md
- Apparently code blocks don't work inside of `<highlight>`
- Fix broken link
> Minor fixes debian install instructions

- install/installation-debian.md
We've recently added packages for 22.04.
> Add Ubuntu 22.04 (Jammy Jellyfish) to supported distros

- install/installation-windows/index.md
The name of the database while connecting via psql is wrong. It is currently `tutorial` but on the step before, we created `example` database. I also verified this while following the instructions and it was indeed wrong.
- Latest (Default)
Fixes #1069
> Fixed the typo in Windows Installation Page

- promscale/installation/kubernetes.md
Because we did an alpha release the autogenerated K8s manifest file points to that alpha release
> Fix link to manifest file which is using alpha version

- promscale/manage-data/retention.md
`currentVersion` was missing a colon so the link was going to
https://docs.timescale.com/promscale/latest/promscale/:currentVersion/installation/
which doesn't exist.
> Fix broken Promscale link

- promscale/installation/index.md
The Promscale extension modifies the `search_path` of the database that it's installed into. This is for convenience of querying from SQL. For advanced Postgres users, this may be unexpected behaviour, so we would like to bring it to their attention.
Fixes https://github.com/timescale/promscale_extension/issues/322
> Add note on Promscale extension search_path modification

- api/distinct_count.md
- api/hyperloglog.md
- api/rollup-hyperloglog.md
- api/stderror.md
Update the hyperloglog documentation to recommend a minimum bucket
size of 1024.  Also update all examples to use larger bucket sizes.
Fixes https://github.com/timescale/product/issues/236
> Update hyperloglog with bucket guidance

- api/hyperloglog.md
- api/tdigest.md
Saw that the hyperloglog page had a mistaken reference to tdigest.
> fix typo in api/hyperloglog.md

- promscale/installation/docker.md
- promscale/installation/kubernetes.md
- promscale/installation/source.md
From google analytics, I see there is a drop in audience engagement from install instructions to send data. In this PR we want to explicitly mention the send data instruction post-installation of Promscale.
> Add send data as note in install instructions

- promscale/installation/kubernetes.md
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
Update promscale helm references to point to latest [release 0.13.0](https://github.com/timescale/promscale/releases/tag/0.13.0
).
> promscale: update links to point to release 0.13.0

- timescaledb/how-to-guides/compression/about-compression.md
Fix typo "for a for a" -> "for a" in compression how-to.
Re: https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression/#disable-compression
> [How-tos] Fix typo "for a for a" -> "for a"

- promscale/manage-data/delete-data.md
In https://github.com/timescale/promscale_extension/pull/437 we adjusted how this function behaves.
Related to https://github.com/timescale/promscale_extension/pull/437
Fixes https://github.com/timescale/docs/issues/1332
> Can only exec ps_trace.delete_all_traces() when Promscale not running

- timescaledb/how-to-guides/upgrades/upgrade-docker.md
Change the instructions for Docker update to use the TimescaleDB HA that includes Toolkit. The install instructions already point to the TimescaleDB HA image. https://docs.timescale.com/install/latest/installation-docker/#install-self-hosted-timescaledb-from-a-pre-built-container
N/A
> Upgrade instructions for Toolkit in Docker

- cloud/index.md
Adding the `ap-southeast-2` region to the list of available regions on Cloud ☁️ 
(me)
> Add ap-southeast-2 (Sydney) to the region list

- timescaledb/how-to-guides/hypertables/hypertables-and-unique-indexes.md
We should add `time` into unique index definition. Device_id is already added.
> Partiotioning Column is time

- promscale/installation/docker.md
Updated the docker installation instructions for promscale to include an environment variable that will run the timescaledb-tune tool with the "promscale" profile.
> Add TSTUNE_PROFILE var to docker cmd for promscale

- install/installation-docker.md
The location of pgdata in pg 14 is now different:
``` rajakavithakodhandapani@RajakavthasMBP2 ~ % docker run -d --name timescaledb -p 127.0.0.1:5432:5432 \
-e POSTGRES_PASSWORD=Sc0rpi0n timescale/timescaledb-ha:pg14-latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2ead1633a6364c4224e4086282df2fa6ba225d7d1f39d6369b1b8e787a3a76e4
rajakavithakodhandapani@RajakavthasMBP2 ~ % psql -U postgres -h localhost
Password for user postgres: 
psql (14.4, server 14.5 (Ubuntu 14.5-1.pgdg22.04+1))
Type "help" for help.
postgres=# SHOW data_directory;
data_directory       
----------------------------
/home/postgres/pgdata/data
(1 row)
postgres=# 
```
Fixes …
> [update]Install self-hosted TimescaleDB from a pre-built container

- timescaledb/how-to-guides/hyperfunctions/function-pipelines.md
Adds a missing backtick that makes a table element not be code formatted:
https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/function-pipelines/#all-function-pipeline-elements
> Add a missing backtick

- _partials/_caggs-function-support.mdx
- timescaledb/how-to-guides/continuous-aggregates/create-index.md
Indexes can now be created directly on caggs by using the view name.
`ORDER BY` is supported in general, not just in the ordered-set
aggregates.
Fixes #1494 
> Document cagg improvements

- install/installation-kubernetes.md
Fixed a typo.
Validated here:
```
rajie@RajakavithasMBP ~ % MASTERPOD="$(kubectl get pod -o name --namespace default -l release=test,role=master)"
rajie@RajakavithasMBP ~ %  kubectl exec -i --tty --namespace default ${MASTERPOD} -- psql -U postgres
Defaulted container "timescaledb" out of: timescaledb, tstune (init)
psql (13.4 (Ubuntu 13.4-1.pgdg21.04+1))
Type "help" for help.
postgres=# CREATE database tsdb;
CREATE DATABASE
postgres=# \c tsdb
You are now connected to database "tsdb" as user "postgres".
tsdb=# \dx
List of installed extensions
Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
plpgsql     | 1.0     | pg_catalog | …
```
> [update] fixed a typo in the command

- api/create_distributed_hypertable.md
- api/create_hypertable.md
- timescaledb/how-to-guides/configuration/configuration.md
This change introduces a new `distributed` argument to the
`create_hypertable()` function as well as two new GUC's to
control its default behaviour: `timescaledb.hypertable_distributed_default`
and `timescaledb.hypertable_replication_factor_default`.
The main idea of this change is to allow automatic creation
of the distributed hypertables by default.
https://github.com/timescale/timescaledb/pull/4545
> Add hypertable distributed argument and defaults

- _partials/_plan_upgrade.mdx
The link to the upgrade postgresql docs page was broken and ended up in a 404.
> Fixed broken link in the _plan_upgrade.mdx

- timescaledb/tutorials/grafana/visualizations/candlestick.md
As a test, add custom meta image for the candlestick tutorial in Grafana.
Issue https://github.com/timescale/web-documentation/issues/395
> Add custom meta image

- api/create_hypertable.md
Fixes a link that wasn't linked right in the `create_hypertable` documentation.
https://docs.timescale.com/api/latest/hypertable/create_hypertable/
> Fix link in create_hypertable docs

- timescaledb/overview/core-concepts/hypertables-and-chunks/hypertable-architecture.md
The link to the chunk sizing docs page was broken and ended up in a 404.
> Fixed broken link in the hypertable-architecture.md

- api/hyperloglog.md
Updates the HyperLogLog documentation:
- Emphasizes the warning about low bucket count: using a value for buckets that's less than 1024 results in very poor
accuracy, and is almost never wanted.
- Remove outdated claim about poor performance with low cardinality: this used to be true, but no longer is, since Toolkit now uses HyperLogLog++ which has better accuracy for low cardinality data.
https://docs.timescale.com/api/latest/hyperfunctions/approx_count_distincts/hyperloglog/
> Improve HyperLogLog documentation

- timescaledb/overview/core-concepts/hypertables-and-chunks/hypertable-architecture.md
This PR fixes a link to documentation on chunk sizing.
The link now points to [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables/#best-practices-for-time-partitioning/) instead of a 404 page.
> Fix chunk size link

- api/saturating_add_pos.md
- api/saturating_sub_pos.md
Fixes two formatting issues in the documentation for saturating math
https://docs.timescale.com/api/latest/hyperfunctions/saturating_math/saturating_add_pos/
https://docs.timescale.com/api/latest/hyperfunctions/saturating_math/saturating_sub_pos/
> Improve formatting on saturating math documentation

- _partials/_psql-installation-centos.md
- install/installation-redhat.md
- Installed and validated psql on centos and added the partials
- Added the instructions to run timescaledb-tune
- Validated that the database has to be initialized before running the timescaledb-tune
- Validated that the built-in module has to be disabled in centos8
Fixes https://github.com/timescale/docs/issues/1569
> [update] Install self-hosted TimescaleDB on Red Hat-based systems

- api/average-time-weight.md
- api/integral-time-weight.md
- api/interpolated_average.md
- api/interpolated_integral.md
- api/page-index/page-index.js
- api/time-weighted-averages.md
- api/time_weight.md
- timescaledb/how-to-guides/hyperfunctions/function-pipelines.md
- timescaledb/how-to-guides/hyperfunctions/time-weighted-averages.md
Updates documentation for the addition of `integral`/`interpolated_integral` in Toolkit 1.11. I based the content for these based on `average`/`interpolated_average`, since the functions are very similar.
> Update docs for integrals in Toolkit 1.11

- api/first-last-time-counter.md
- api/first-last-time-timeweight.md
- api/first-last-val-counter.md
- api/first-last-val-timeweight.md
- api/page-index/page-index.js
These experimental accessors have been added to work on both time_weight and counter_agg aggregates in Toolkit 1.11.0
> Document `first_val`, `last_val`, `first_time` and `last_time` accessors

- cloud/backup-restore-cloud.md
Updates wording to be "*at least* seven days" for the backup retention period. Also adds some text to the Cloud highlight, since it looks a bit funny without it.
> Updates wording around cloud backup retention

- .github/workflows/failed-builds.yml
The web-documentation repo now dispatches an event if a build from docs content fails. When this event is received, write a comment in the corresponding PR.
> ci(build): comment on pr if build fails

- timescaledb/how-to-guides/continuous-aggregates/compression-on-continuous-aggregates.md
The word `to` appears two times in a row in the `How-to guides` page on compressing continuous integration. 
N/A
> Remove duplicate word

- timescaledb/overview/core-concepts/hypertables-and-chunks/hypertable-architecture.md
- timescaledb/overview/core-concepts/hypertables-and-chunks/hypertables-and-chunks-benefits.md
Fix link source. Probably the source was renamed at some point.
Fixes issue [reported](https://timescaledb.slack.com/archives/C4GT3N90X/p1668200568630899) in the  community slack.
> Fix link source

- timescaledb/how-to-guides/hyperfunctions/install-toolkit.md
Starting with 1.12.0, Toolkit is available to be installed via Homebrew
https://github.com/timescale/homebrew-tap/blob/main/timescaledb-toolkit.rb
> Add instructions for installing Toolkit via Homebrew

- api/first-last-time-counter.md
- api/first-last-time-timeweight.md
- api/first-last-val-counter.md
- api/first-last-val-timeweight.md
These were actually never experimental and have been stable since their introduction in Toolkit 1.11.0
> Remove experimental tag from `{first,last}_{time,val}` accessors

- api/duration_in.md
- api/interpolated_duration_in.md
- api/interpolated_state_periods.md
- api/interpolated_state_timeline.md
- api/into_values-state_agg.md
- api/page-index/page-index.js
- api/rollup-state_agg.md
- api/state-aggregates.md
- api/state_agg.md
- api/state_periods.md
- api/state_timeline.md
Documents all of the changes made to `state_agg` and `timeline_agg` (including the new support for integer states and rollup) in TimescaleDB Toolkit 1.13.
> Document changes to state_agg/timeline_agg in Toolkit 1.13

- timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
Signed-off-by: Hongbo Miao <3375461+Hongbo-Miao@users.noreply.github.com>
Close https://github.com/timescale/docs/issues/1922
Just a small improvement to make it more user friendly. 😃
I originally failed to locate the document mentioned in
https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/
> docs: link the Troubleshooting page

- .github/workflows/deploy.yml
`set-output` is deprecated and the official GitHub advice is to use environment files instead. This commit updates our actions to match.
> Update GitHub Actions to remove set-output

- api/_hyperfunctions/state_agg/interpolated_duration_in.md
- api/_hyperfunctions/timeline_agg/interpolated_duration_in.md
- api/_hyperfunctions/timeline_agg/interpolated_state_periods.md
- api/_hyperfunctions/timeline_agg/interpolated_state_timeline.md
For the state/timeline aggregates, the name of the argument for the aggregate is written as `tws` instead of `agg` in a few parts of the documentation. `tws` stands for Time-Weighted Summary, which is not applicable here. I think I copied from the time-weighted average documentation and forgot to change the parameter name.
> Fix argument name for state/timeline functions

- api/_hyperfunctions/state_agg/state_timeline.md
Fixes the name of the `state_int_timeline` function – it was written in the docs as `state_int_state`.
> Fix state_int_timeline name

- .github/workflows/deploy.yml
Let web docs handle how the branch name will be manipulated, which is more flexible than predetermining it on the sending end.
Related to https://github.com/timescale/docs-private/issues/67
> dispatch unmanipulated branch name to web-docs

- _partials/_where-to-next.md
- self-hosted/install/index.md
- self-hosted/install/installation-cloud-image.md
- self-hosted/install/installation-docker.md
- self-hosted/install/installation-kubernetes.md
- self-hosted/install/installation-linux.md
- self-hosted/install/installation-macos.md
- self-hosted/install/installation-source.md
- self-hosted/install/installation-windows.md
- self-hosted/install/self-hosted.md
- self-hosted/page-index/page-index.js
- aligned content to self-hosted
- replaced references to TimescaleDB with Timescale
- created a partial for Where to next 
- Updated the link in WhereTo Use Timescale
PS: the icons for docker, k8s, and cloud-image are not added in the Install page
Tracking updated: https://docs.google.com/spreadsheets/d/1oQo9EfoGURLFsq4dKgKshRpLLE12gREU3P709Xzq54I/edit?usp=sharing
Fixes https://github.com/timescale/docs-private/issues/77
> [Update] Self-Hosted 

- api/_hyperfunctions/time_weight/integral.md
- api/_hyperfunctions/time_weight/interpolated_integral.md
- Fixes references to "averages" with correct references to "integrals"
- Better indicate `integral`'s `unit` parameter is optional
- Add `unit` to list of optional parameters for `interpolated_integral`
> Improve integral docs

- api/_hyperfunctions/time_bucket_gapfill/time_bucket_gapfill.md
`timezone` is the third argument to `time_bucket_gapfill`, not the last. 
> Fix argument order for time_bucket_gapfill

- api/days_in_month.md
- api/month_normalize.md
- api/to_epoch.md
We stabilized the three date utility functions in Toolkit 1.16. We forgot to document `to_epoch` when it was added, so this PR also documents that function. …
> Document date utility stabilization in Toolkit 1.16

- api/_hyperfunctions/max_n/examples.md
- api/_hyperfunctions/max_n/into_array.md
- api/_hyperfunctions/max_n/into_values.md
- api/_hyperfunctions/max_n/max_n.md
- api/_hyperfunctions/max_n/rollup.md
- api/_hyperfunctions/max_n_by/examples.md
- api/_hyperfunctions/max_n_by/into_values.md
- api/_hyperfunctions/max_n_by/max_n_by.md
- api/_hyperfunctions/max_n_by/rollup.md
- api/_hyperfunctions/min_n/examples.md
- api/_hyperfunctions/min_n/into_array.md
- api/_hyperfunctions/min_n/into_values.md
- api/_hyperfunctions/min_n/min_n.md
- api/_hyperfunctions/min_n/rollup.md
- api/_hyperfunctions/min_n_by/examples.md
- api/_hyperfunctions/min_n_by/into_values.md
- api/_hyperfunctions/min_n_by/min_n_by.md
- api/_hyperfunctions/min_n_by/rollup.md
min_n/max_n/min_n_by/max_n_by were stabilized in Toolkit 1.16.
*   [ ] Have any images been uploaded to the correct location, and are …
> Document min_n/max_n stabilization in Toolkit 1.16

- use-timescale/time-buckets/use-time-buckets.md
Fixes typo 'cna' inside `use-timescale/time-buckets/use-time-buckets.md`
*   [ ] Have any images …
> Fix(typo) in use-time-buckets.md

- use-timescale/data-tiering/untier-data.md
Untiering is now synchronous when `untier_chunk` is called. Updating the docs to remove reference to untiering being asyncronous. 
* …
> Untiering is now a synchronous operation

- .github/workflows/deploy.yml
Deploy on forks fails because it doesn't have access to the required secret.
However, it still attempts to run.
This PR restricts the deploy action to branches of the base repository.
* …
> ci: disable deploy action on forks

- use-timescale/account-management.md
The Highlight component in the account management docs page had a markdown link inside of it, causing it to render incorrectly.
<details><summary>Screenshot</summary>
</details>
*   [ …
> fix: link formatting in Highlight component

- self-hosted/page-index/page-index.js
Removed the pg-dump and restore it from the Index file. Did not remove it from the https://docs.timescale.com/self-hosted/latest/backup-and-restore/ because the Logical back has the link to the page under Use timescale.
Fixes https://github.com/timescale/docs-private/issues/181
*   [ ] Is the content …
> [update] Backup and Restore

- api/add_data_node.md
- api/create_hypertable.md
- self-hosted/distributed-hypertables/create-distributed-hypertables.md
- use-timescale/hypertables/about-hypertables.md
_ removed the references to the space partition in examples
_ removed the references to the space partition in create_hypertable sections
_ retained the references only in distributed hyper table sections
Fixes https://github.com/timescale/docs/issues/2595
*   [ …
> [update] remove references to space partition

- quick-start/ruby.md
The extension should already be loaded when connecting to a Timescale service or installing TimescaleDB so the instructions don't need a migration to add the extension to a postgres database
*   [ ] Have any images been uploaded to the correct location, and are …
> Remove loading extension step from Ruby quick start

- api/add_retention_policy.md
In https://github.com/timescale/timescaledb/pull/4384, the `schedul_interval` parameter was added to `add_compression_policy` and `add_retention_policy` functions.
However, the documentation for `add_retention_policy` does not include an explanation for this parameter.
I just copied the explanation from the  [`add_compression_policy` page](https://docs.timescale.com/api/latest/compression/add_compression_policy/). Please let me know if it is not appropriate.
*   [ ] Is the content presented in a …
> Add schedule_interval param in add_retention_policy

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy.yml
Dispatch to the web-documentation repository broke, presumably because
the PAT which was being used for it expired. This change uses the
org-wide PAT associated with the timescale-automation account.
> Fix deploy

- api/add_compression_policy.md
Remove note that Compression policies on continuous aggregates  should be set up so that they do not overlap with refresh policies on continuous aggregates.
This is not true any more since mutable compression has been rolled out
*   [ ] Have any images been …
> Remove note about Compression policies on continuous aggregates

- _partials/_migrate_dual_write_backfill_getting_help.md
- migrate/pg-dump-and-restore/index.md
- migrate/pg-dump-and-restore/pg-dump-restore-from-postgres.md
- migrate/pg-dump-and-restore/pg-dump-restore-from-timescaledb.md
It turns out that reference links aren't supported in the body of a `<Highlight>` component.
There is another issue with `:currentVersion:` not being supported in links used in a `<Highlight>` component, for which I've opened a companion PR: https://github.com/timescale/web-documentation/pull/666
> Fix broken links in migration documentation

- api/create_hypertable.md
The content which this link was pointing to was removed a while ago, so it doesn't make sense to change the link to the new migration section.
Fixes the failing markdown link check: https://github.com/timescale/docs/actions/runs/6305809897/job/17119882687
> Remove dead link to migration

- api/add_compression_policy.md
This PR updates the documentation regarding the changed default value of the schedule_interval parameter of the compression_policy (see https://github.com/timescale/timescaledb/pull/6102).
The default value of the `schedule_interval` parameter will change after https://github.com/timescale/timescaledb/pull/6102 is merged and released.
*   [ ] Does the content provide …
> Adjusted schedule_interval of compression policy

- api/refresh_continuous_aggregate.md
After call the `refresh_continuous_aggregate` procedure we should execute a `COMMIT` because the refresh cannot execute into transaction.
Related to timescale/timescaledb#6124
> Fix incremental cagg refresh example

- use-timescale/continuous-aggregates/hierarchical-continuous-aggregates.md
The hierarchical CAgg example does not calculate a concrete value. Instead, a `uddsketch` is produced which is hard to understand:
```
(version:1,alpha:0.001,max_buckets:200,num_buckets:5,compactions:0,count:6,sum:59.82,buckets:[(Positive(805),2),(Positive(1256),1),(Positive(1259),1),(Positive(1263),1),(Positive(1267),1)]))
```
This PR changes the CAgg definition to provide a concrete `mean` value. 
*   [ ] …
> Improved hierarchical caggs example

- _troubleshooting/cagg-watermark-in-future.md
- _troubleshooting/scheduled-jobs-stop-running.md
- self-hosted/multinode-timescaledb/multinode-maintenance.md
We updated all references to functions in the `_timescaledb_internal` schema to point to `_timescaledb_functions`, in line with the changes which were released in TimescaleDB 2.12.
Users who do no yet have the privilege of using 2.12 may be confused by the documentation.
> Fix references to _timescaledb_functions for pre-2.12

- migrate/troubleshooting.md
- use-timescale/troubleshoot-timescaledb.md
Documentation of the new GUC `timescaledb.bgw_log_level`.
It also fixes some missing "code quotes" for things like `pg_dump` and `pg_restore`.
Fixes #2738  …
> Add documentation for timescaledb.bgw_log_level

- use-timescale/ha-replicas/high-availability.md
Clarify that the read-replica connection is not highly available for reads during replica recovery.
> Add clarification about read-replica connection during failover

- api/alter_table_compression.md
- Clarify that ALTER compression command should often be used  in combination with compression policy or compress_chunk
- Clarify that segmentby is important field
> Clarify that ALTER compression command does not compress itself

- self-hosted/configuration/about-configuration.md
- self-hosted/configuration/configuration.md
max_locks_per_transaction is multiplied by max_connections which is the hard limit for how many locks can exist at the same time.
> Fix documentation about max_locks_per_transaction

- api/create_distributed_hypertable.md
With the introduction of the new hypertable api, some of the links on the distributed hypertable api doc page were broken.
> Fix broken links in distributed hypertable docs

- use-timescale/account-management.md
Fixes a broken link to timescale.com/enterprise.
Note: the link is not yet live, but will be going live later today. The current preview is here: http://www-dev.timescale.com.s3-website-us-east-1.amazonaws.com/2499-merge/enterprise and the backing PR is here: https://github.com/timescale/web-splash/pull/2499
> Fix broken link to enterprise page

- use-timescale/data-tiering/about-data-tiering.md
- use-timescale/data-tiering/index.md
- use-timescale/data-tiering/querying-tiered-data.md
- use-timescale/data-tiering/tour-data-tiering.md
- use-timescale/page-index/page-index.js
Add getting started guide for Data tiering …
> Add getting started guide for Data Tiering

- api/alter_table_compression.md
People were getting under the impression only compressed chunks are going to be merged when in fact rollup merges chunks irreversibly. 
Fixes https://github.com/timescale/timescaledb/issues/6260
*   [ ] Does the content …
> Update rollup docs about creating larger chunks

- _partials/_migrate_from_timescaledb_version.md
- migrate/dual-write-and-backfill/dual-write-from-other.md
- migrate/live-migration/index.md
- migrate/pg-dump-and-restore/pg-dump-restore-from-timescaledb.md
- self-hosted/install/installation-kubernetes.md
- tutorials/OLD_grafana/installation.md
- tutorials/financial-ingest-real-time/financial-ingest-dataset.md
- Fix missing import statements
When import statements are missing for partial components, the content is not present, and the build passes without a problem. Some warnings are emitted, but it appears as though there are some false positives.
- Tweak migration docs
Add the "Getting Help" partial to the "dual-write from other" page, use correct type for Highlight.
> Fix missing import statements, tweak migration docs

- use-timescale/page-index/page-index.js
Fix up the broken page looking for `pitr`  …
> Fix page-index.js to use point-in-time-recovery instead of pitr
