- timescaledb/how-to-guides/replication-and-ha/replication.md
> [fix] Fix typo

- timescale-cloud/cloud-multi-node.md
- timescale-forge/forge-multi-node.md
- timescaledb/getting-started/next-steps.md
- timescaledb/how-to-guides/hypertables/best-practices.md
- timescaledb/quick-start/golang.md
> Fix hypter typos

- timescaledb/how-to-guides/update-timescaledb/update-timescaledb-2.md
This will fix an indentation error on the how-to-guides > update-timescaledb-2 file
> [fix] Fix indentation on how-to-guides > update-timescaledb-2

- timescaledb/quick-start/python.md
- timescaledb/tutorials/index.md
> Fix a few links

- .github/workflows/deploy.yml
- README.md
> testing CI

- timescaledb/tutorials/promscale/index.md
Reported by Mat on Slack. Just a path change.
> Update link paths for promscale pages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/rfc.md
> Update issue templates

- api/compression.md
- timescaledb/how-to-guides/compression/backfill-historical-data.md
- timescaledb/how-to-guides/compression/compression-basics.md
- timescaledb/how-to-guides/compression/decompress-chunks.md
Support modifications to compressed data.
https://github.com/timescale/timescaledb/pull/3230
> Support inserting into compressed chunks

- api/compression.md
Fixing broken links at the top and modifying the table
> Fix links in compression landing page and table of supported versions

- timescale-forge/disk-management.md
- timescale-forge/page-index/page-index.js
Adds a new section for Forge disk management, based on blog post for same.
Fixes https://github.com/timescale/docs/issues/68
> Forge disk management

- timescaledb/how-to-guides/distributed-hypertables/alter.md
Add a missing link.
- [x ] Latest (Default)
> Fix missing link in ALTER for distributed hypertables

- timescale-forge/forge-multi-node.md
If you use uppercase letters in the node names, you won't be able to create a user mapping for them later on.
...
> add note about lowercase node names

- timescale-forge/create-a-service.md
Updates the Forge screenshots in the Forge "Create a Service" tutorial to reflect changes in the UI.
Fixes https://github.com/timescale/docs/issues/65
> Update Forge screenshots

- timescaledb/quick-start/python.md
Updated python guide, reorganized the 3rd and 4th section ("(Insert a batch of rows into TimescaleDB) ") and simplified a few things. Also tried to follow the structure of the other language guides we have
> Update python guide

- timescaledb/how-to-guides/install-timescaledb/installation-yum.md
Fix two broken xrefs, and remove unused links.
> Fix broken links

- timescaledb/tutorials/time-series-forecast.md
This tutorial had a number of broken links, this PR fixes them. 
H/T @lucieva
> fix 404 links

- timescale-forge/customize-configuration.md
This adds some content about Forge extensions. The original request asked for a new page, but I wasn't sure there was enough content here to warrant it. Happy to discuss, though.
Fixes https://github.com/timescale/docs/issues/57
> Adds note about pg extensions to Forge customize section

- timescaledb/how-to-guides/compression/backfill-historical-data.md
- timescaledb/how-to-guides/user-defined-actions/alter-and-delete.md
- timescaledb/how-to-guides/user-defined-actions/alter-or-drop.md
- timescaledb/how-to-guides/user-defined-actions/create-and-register.md
- timescaledb/how-to-guides/user-defined-actions/examples.md
- timescaledb/how-to-guides/user-defined-actions/test-and-debug.md
- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
A number of links were not pointing to the correct API location and other misc. link fixes.
#109, #110, #111, #112, #113, #114
> Fixes to Actions documentation

- api/add_dimension.md
- api/continuous-aggregates.md
- timescaledb/how-to-guides/multi-node-setup/required-configuration.md
Fixes broken links in three pages
> Fixes broken links

- timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
- timescaledb/how-to-guides/compression/compression.md
- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
Fixes 404s, mostly broken anchors 😕
> Fix 404s discovered by Moz

- timescaledb/how-to-guides/compression/compression.md
- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
> Fix 404s reported by Moz

- timescaledb/quick-start/node.md
One of the examples has a syntax error.
> Add missing simple quote

- timescaledb/how-to-guides/install-timescaledb/installation-ubuntu-ami.md
Updated AMIs to:
eu-central-1: ami-01149ee2f1589f9e4
eu-north-1: ami-001b590df85e1b07d
eu-west-1: ami-03aeb656eaa7b3e88
eu-west-2: ami-036001e38f1774a9a
eu-west-3: ami-034a707417a64712f
us-east-1: ami-08caf7e46604e1195
us-east-2: ami-063deccec7d552047
us-west-1: ami-02e3e3080de31f4fb
us-west-2: ami-0a8a1ee905dca7075
> Added AMIs for 2.3.1

- timescaledb/how-to-guides/ingest-data.md
- timescaledb/how-to-guides/install-timescaledb/installation-ubuntu-ami.md
- timescaledb/how-to-guides/multi-node-setup/node-communication.md
A number of issues have been raised about broken links, this PR fixes them.
- Fixes https://github.com/timescale/docs/issues/140
- Fixes https://github.com/timescale/docs/issues/143
- Fixes https://github.com/timescale/docs/issues/145
- Fixes https://github.com/timescale/docs/issues/148
- Fixes https://github.com/timescale/docs/issues/139
> Fix multiple broken links

- timescaledb/overview/faq/faq-products.md
- timescaledb/overview/faq/index.md
- timescaledb/overview/page-index/page-index.js
Noticed some of the FAQs were incorrect or sparsely populated. Cleaned up the verbiage.
- [ X] Older [specify]
> Cleaned up some of the FAQs

- api/percentile-approximation.md
- api/time-weighted-averages.md
- timescaledb/how-to-guides/install-timescaledb-toolkit.md
- timescaledb/how-to-guides/page-index/page-index.js
Adding a quick and dirty install section that will get further updates as more functions are released and packages are supported.
> Adding very limited install instructions for launch to be revised later.

- api/percentile_agg.md
- timescaledb/how-to-guides/query-data/advanced-analytic-queries.md
@mirandaauhl noticed a few broken links from last-minute reorg.
> url fixes based on internal conversation/404 errors

- timescaledb/overview/core-concepts/continuous-aggregates.md
- timescaledb/overview/core-concepts/hypertables-and-chunks.md
- timescaledb/overview/core-concepts/index.md
- timescaledb/overview/core-concepts/scaling.md
Fixed some small content issues in TimescaleDB core concepts doc
> Minor improvements to several pages in the TimescaleDB core concepts

- timescaledb/tutorials/nfl-fantasy-league.md
Add to the analyze section
notes: I do not have access to the aws image location so the images still need to be uploaded. 
merging into the nfl-tutorial branch for nfl tutorial
none
> Add to query section

- .github/workflows/deploy-prod.yml
add search update to deploy process
> add webhook

- timescaledb/tutorials/custom-timescaledb-dashboards.md
Just adding a thumbnail to make it more attractive.
> Add video thumbnail

- timescaledb/tutorials/index.md
- timescaledb/tutorials/nfl-analytics/advanced-analysis.md
- timescaledb/tutorials/nfl-analytics/index.md
- timescaledb/tutorials/nfl-analytics/ingest-and-query.md
- timescaledb/tutorials/nfl-analytics/play-visualization.md
- timescaledb/tutorials/page-index/page-index.js
Wanted to create a separate PR so that we could fix any reorg before merging into the main NFL branch. Please review the link and mostly limit comments to organization. Any major query changes (mostly) please keep for a final review of the main branch.
> reorganization of the NFL tutorial, breaking it up into multiple pages.

- timescaledb/tutorials/nfl-analytics/advanced-analysis.md
- timescaledb/tutorials/nfl-analytics/play-visualization.md
fix hyperlinks and add conclusion
Latest
> Nfl fix 403

- timescaledb/tutorials/nfl-analytics/advanced-analysis.md
- timescaledb/tutorials/nfl-analytics/play-visualization.md
The links are still wonky. Putting in updates so that they work
latest
> update links to work

- timescaledb/how-to-guides/install-timescaledb/installation-apt-ubuntu.md
> Ubuntu packagecloud

- timescaledb/tutorials/nfl-analytics/ingest-and-query.md
update sql and python commands to work properly
Latest
> update sql and python scripts to work properly

- timescaledb/tutorials/nfl-analytics/advanced-analysis.md
- timescaledb/tutorials/nfl-analytics/ingest-and-query.md
- timescaledb/tutorials/nfl-analytics/join-with-relational.md
We ingest the data with a different column name then what we used for testing, had to update all the queries to use the correct column names
Latest
> needed to correct a column name because of ingest

- timescaledb/overview/release-notes/index.md
> TimescaleDB 2.4.1 Release notes

- .github/workflows/deploy-prod.yml
Remove broken update search index
> remove update search index for now

- timescaledb/how-to-guides/ingest-data.md
- timescaledb/integrations/ingesting-data.md
- timescaledb/tutorials/grafana/installation.md
Fix links reported by automated link checker.
- Fixes: https://github.com/timescale/docs/issues/284
- Fixes: https://github.com/timescale/docs/issues/271
> Fix links reported by link checker.

- timescaledb/how-to-guides/troubleshoot-timescaledb.md
Replace &lt; and &gt; with actual angle brackets in code block
Fixes:
> Fix angle brackets in code block

- timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
- timescaledb/tutorials/aws-lambda/create-data-api.md
- timescaledb/tutorials/aws-lambda/index.md
- timescaledb/tutorials/page-index/page-index.js
Adding the TimescaleDB with AWS Lambda tutorial. (previous discussions happened in [Google docs](https://docs.google.com/document/d/1DkTZkak8-vNYJwVv2oVMGZ1D7KI9lYfI-RnJNwHDkZE/edit#))
https://docs-dev.timescale.com/docs-tutorial-aws-lambda/timescaledb/tutorial-aws-lambda/tutorials/aws-lambda/
> Add TimescaleDB with AWS Lambda tutorial

- timescaledb/how-to-guides/install-timescaledb/installation-apt-debian.md
- timescaledb/how-to-guides/install-timescaledb/installation-yum.md
Add mention of debian 11 to docs
> Mention debian 11 in docs

- README.md
Also not sure if there are more highlight types that could be used besides these?
> Add "note" as possible highlight type in readme

- timescaledb/how-to-guides/hypertables/best-practices.md
> Fix typo in hypertable best practices

- timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
- timescaledb/tutorials/aws-lambda/create-data-api.md
- timescaledb/tutorials/aws-lambda/index.md
- timescaledb/tutorials/page-index/page-index.js
Edits to the new AWS Lambda tutorial, mostly syntax.
cc @lucieva for visibility
> AWS Lambda tutorial review

- timescaledb/how-to-guides/user-defined-actions/example-tiered-storage.md
Removes errant semi-colon
Fixes https://github.com/timescale/docs/issues/323
> Fixes typo in SQL

- api/move_chunk.md
add leading slash, and version
Fixes https://github.com/timescale/docs/issues/339
> Fix bad path

- timescaledb/tutorials/custom-timescaledb-dashboards.md
This query was the victim of a terrible copypasta attack! This PR changes to the correct query.
Fixes https://github.com/timescale/docs/issues/326
> Fix incorrect sql query

- mst/create-a-service.md
- mst/index.md
- mst/ingest-data.md
- mst/maintenance.md
- mst/metrics-datadog.md
- mst/mst-multi-node.md
- mst/security.md
- mst/troubleshooting.md
- mst/user-management.md
- mst/viewing-service-logs.md
- mst/vpc-peering.md
Small edits for wording and syntax.
> editing pass for wording & syntax

- timescaledb/tutorials/page-index/page-index.js
Add metadata to tsdb Tutorial index
> Add metadata for tutorials

- timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
- timescaledb/tutorials/aws-lambda/create-data-api.md
Fixed some broken image links and added placeholders where needed
> AWS Lambda tutorial quick fixes

- timescaledb/quick-start/page-index/page-index.js
Add metadata to tsdb Code Quick Starts index
> Add metadata for code quick starts

- timescaledb/getting-started/page-index/page-index.js
Add metadata to tsdb Getting Started index
> Add metadata for Getting Started

- timescale-cloud/maintenance.md
- timescale-forge/maintenance.md
- timescale-forge/page-index/page-index.js
Create new page for maintenance windows on Forge.
- Fixes https://github.com/timescale/docs/issues/311
- Fixes https://github.com/timescale/docs/issues/331
> Forge - Maintenance Windows

- .github/workflows/broken-markdown-links.yml
> add excludes

- timescaledb/getting-started/create-hypertable.md
This page will be overhauled properly when I get to the Getting Started Guide, but for now this is a quick line edit to improve it.
Fixes https://github.com/timescale/docs/issues/413
> General edits to create hypertable getting started page

- timescaledb/overview/index.md
Just a line edit.
Fixes https://github.com/timescale/docs/issues/436
> Light editing to clarify overview

- timescale-cloud/connection-pools.md
- timescale-cloud/index.md
- timescale-cloud/ingest-data.md
- timescale-cloud/metrics-datadog.md
> remove mst to cloud

- timescaledb/getting-started/create-cagg.md
- timescaledb/how-to-guides/continuous-aggregates/create-a-continuous-aggregate.md
Couple of small syntax edits, and correcting a typo
Fixes https://github.com/timescale/docs/issues/468
> Small edits to caggs content

- api/approx_percentile.md
- api/approx_percentile_rank.md
- api/average.md
- api/error.md
- api/max_val.md
- api/mean.md
- api/min_val.md
- api/num_vals.md
- api/percentile-aggregation-methods.md
- api/percentile-approximation.md
- api/percentile_agg.md
- api/rollup-percentile.md
- api/rollup-timeweight.md
- api/tdigest.md
- api/time-weighted-averages.md
- api/time_weight.md
- api/uddsketch.md
> add toolkit tag

- timescaledb/getting-started/launch-timescaledb.md
This updates the screenshots for all pages under the Timescale Cloud section: https://docs.timescale.com/timescaledb/latest/getting-started/
Please click through the pages on the preview to make sure all images are rendering OK
> Update screenshots for new branding - Getting Started section

- mst/index.md
- timescaledb/how-to-guides/install-timescaledb-toolkit.md
- timescaledb/tutorials/page-index/page-index.js
> update sidebar to mst

- timescaledb/tutorials/page-index/page-index.js
- timescaledb/tutorials/promscale/index.md
Update title of Promscale tutorial to make it clear it's using Prometheus (in preparation for future Promscale tutorials)
> Update title of Promscale tutorial

- cloud/cloud-multi-node.md
- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
- timescaledb/how-to-guides/multinode-timescaledb/about-multinode.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-setup.md
> add slashes

- CONTRIBUTING.md
- promscale/install-promscale.md
- timescaledb/how-to-guides/backup-and-restore/docker-and-wale.md
- timescaledb/how-to-guides/backup-and-restore/pg-dump-and-restore.md
- timescaledb/how-to-guides/backup-and-restore/timescaledb-backup.md
- timescaledb/how-to-guides/compression/about-compression.md
- timescaledb/how-to-guides/compression/decompress-chunks.md
- timescaledb/how-to-guides/compression/manually-compress-chunks.md
- timescaledb/how-to-guides/continuous-aggregates/create-a-continuous-aggregate.md
- timescaledb/how-to-guides/continuous-aggregates/drop-data.md
- timescaledb/how-to-guides/continuous-aggregates/materialized-hypertables.md
- timescaledb/how-to-guides/continuous-aggregates/real-time-aggregates.md
- timescaledb/how-to-guides/continuous-aggregates/refresh-policies.md
- timescaledb/how-to-guides/continuous-aggregates/time.md
- timescaledb/quick-start/dotnet.md
- timescaledb/tutorials/aws-lambda/3rd-party-api-ingest.md
- timescaledb/tutorials/aws-lambda/continuous-deployment.md
- timescaledb/tutorials/aws-lambda/create-data-api.md
- timescaledb/tutorials/grafana/installation.md
adds procedure styling to rest of docs
> add procedure styling to rest of docs

- timescaledb/how-to-guides/install-timescaledb/installation-apt-debian.md
- timescaledb/how-to-guides/install-timescaledb/installation-apt-ubuntu.md
- timescaledb/how-to-guides/install-timescaledb/installation-homebrew.md
- timescaledb/how-to-guides/install-timescaledb/installation-source-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-source.md
- timescaledb/how-to-guides/install-timescaledb/installation-windows.md
- timescaledb/how-to-guides/install-timescaledb/installation-yum.md
Add PG14 in a couple missing places.
> Add PG14 to the installation pages

- timescaledb/how-to-guides/continuous-aggregates/real-time-aggregates.md
> Update sql in RT aggs section

- .github/workflows/deploy-prod.yml
> add back scraper

- .github/workflows/link-checker.yml
- mlc_config.json
> add link checker

- .github/workflows/link-checker.yml
> switch link checker to latest

- timescaledb/how-to-guides/multinode-timescaledb/multinode-ha.md
Make it clear in the multi-node HA section that there are two viable
ways to provide multi-node HA. In particular, we should emphasize that
native replication is still not recommended for production use and
suggest setting up standby nodes as an alternative.
The change also fixes a couple of issues like text that ends in the
middle of the sentence, missing content that existed in old docs, etc.
Fixes https://github.com/timescale/docs/issues/596
> Improve the multi-node HA section

- timescaledb/tutorials/analyze-cryptocurrency-data.md
Adds error handling so that missing coins are skipped.
Fixes https://github.com/timescale/docs/issues/542
> Add skip to for loop

- timescaledb/quick-start/python.md
Fixes https://github.com/timescale/docs/issues/552
> Add missing variables to Python code sample

- api/move_chunk_experimental.md
- cloud/disk-management.md
- timescaledb/how-to-guides/hyperfunctions/approximate-percentile.md
- timescaledb/how-to-guides/hypertables/create.md
- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-setup.md
> round of 404 cleanup

- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> Less `e` on distributed-hypertables.md

- timescaledb/how-to-guides/continuous-aggregates/about-continuous-aggregates.md
- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-setup.md
Adds some tips about using caggs on multi-node to the caggs section, and some xrefs in the multi-node and distributed hypertables section.
Fixes https://github.com/timescale/docs-private/issues/14
> Add content about caggs on multi-node, plus pointers

- timescaledb/overview/release-notes/index.md
> 2.5.1 Release notes

- timescaledb/tutorials/analyze-nft-data/index.md
- timescaledb/tutorials/analyze-nft-data/nft-schema-ingestion.md
Editing instructions due to OpenSea requiring an API key to fetch data. ([tweet](https://twitter.com/apiopensea/status/1461135305193443334))
> Fix NFT tutorial (API key needed)

- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
- timescaledb/tutorials/aws-lambda/create-data-api.md
Expand the Lambda tutorial with inserting function using AWS Lambda + API Gateway to insert data into TimescaleDB
https://docs-dev.timescale.com/docs-lambda-post-api/timescaledb/lambda-post-api/tutorials/aws-lambda/create-data-api/#create-a-new-lambda-function-to-insert-data-into-the-database
> Expand the Lambda tutorial with inserting function

- timescaledb/how-to-guides/hypertables/create.md
Created this PR to start contributing to TimescaleDB documentation.
- [*] Latest (Default)
- Partial https://github.com/timescale/docs/issues/642
> Updated the examples and schema to be consistent

- timescaledb/tutorials/promscale/promscale-run-queries.md
Fixed formatting in SQL output tables.
> Fixed the table formatting issue

- .github/workflows/vale-linter.yml
> continue on error for vale

- promscale/installation/docker.md
Improve readability of command by breaking it up into multiple lines
> Break long command into multiple lines

- api/create_materialized_view.md
Minor change from https://github.com/timescale/docs/pull/609#discussion_r778472031
> Minor reorg following on from PR#609

- timescaledb/index.md
- timescaledb/tutorials/index.md
(https://github.com/timescale/docs/issues/701)
> update promscale tutorials

- api/create_hypertable.md
https://github.com/timescale/docs/issues/713
> add trailing slashes

- api/create_hypertable.md
> remove e.g.

- timescaledb/overview/core-concepts/continuous-aggregates.md
Not all users may be familiar with the concept of aggregate queries. Adding examples to illustrate. Feel free to change or discard this proposal.
N/A
> add a hint of what is an aggregate query

- api/move_chunk_experimental.md
- api/time-weighted-averages.md
- install/installation-mst.md
- install/installation-source.md
- install/installation-windows.md
- promscale/installation/prom-migrator.md
- timescaledb/how-to-guides/configuration/about-configuration.md
- timescaledb/how-to-guides/continuous-aggregates/real-time-aggregates.md
- timescaledb/how-to-guides/hypertables/create.md
- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
> add 404 fixes

- timescaledb/how-to-guides/hypertables/distributed-hypertables.md
Add a small clarification about expectations around update/delete
operations when distributed hypertables are involved.
As above in commit message
Fixes documentation requirements arising from https://github.com/timescale/Support-Dev-Collab/issues/216
> Clarify about distributed UPDATE/DELETE

- timescaledb/how-to-guides/hyperfunctions/about-hyperfunctions.md
> Fix typo in About Hyperfunctions

- timescaledb/getting-started/create-cagg.md
- timescaledb/how-to-guides/connecting/psql.md
- Fix broken link to homebrew install guide
- Fix capitalization inconsistency in SQL query
Fixes #744
> Fix broken link and capitalization inconsistency

- api/time_bucket.md
Add explicit cast to time_bucket sample usage
Fixes https://github.com/timescale/docs/issues/728
> Add explicit cast to time_bucket

- timescaledb/how-to-guides/configuration/timescaledb-tune.md
Updates instructions to full path for Timescale Tune
Fixes https://github.com/timescale/docs/issues/734
> Update to full path

- timescaledb/how-to-guides/multinode-timescaledb/multinode-maintenance.md
Local auto-vacuum is not useful to update statistics on distributed
hypertables. Add a section about using a job to periodically call
ANALYZE on distributed hypertables.
As mentioned in above commit message 
Fixes documentation requirements arising from https://github.com/timescale/timescaledb/issues/3770
> Add maint job for distributed analyze

- cloud/metrics.md
- cloud/page-index/page-index.js
Adds metrics page to Cloud docs
Fixes https://github.com/timescale/docs/issues/720
> Cloud ops lana

- install/installation-cloud-image.md
- timescaledb/contribute-to-docs.md
- timescaledb/overview/core-concepts/scaling.md
> Fix miscellaneous typos and emojis

- timescaledb/how-to-guides/ingest-data.md
* Updated Kafka references to mention full name of connector.
* Edited entire page for word usage, grammar, style, etc.
* Checked, updated, and removed unused links
Fixes https://github.com/timescale/docs/issues/577
> Fixed mention of Kafka Connect

- timescaledb/how-to-guides/migrate-data/index.md
This page was a mess, tidied it up.
Drive-by edits from https://github.com/timescale/docs/issues/538
> Light editing in the Migrate Data index

- timescaledb/overview/core-concepts/user-defined-actions.md
Adds an example of creating a table and procedure to user defined actions overview.
Fixes https://github.com/timescale/docs/issues/686
> Add example to user defined actions.

- timescaledb/how-to-guides/continuous-aggregates/about-continuous-aggregates.md
Command should have read `CREATE MATERIALIZED VIEW` instead of `CREATE VIEW`.
Fixes https://github.com/timescale/docs/issues/676
> fix create view command

- timescaledb/overview/core-concepts/user-defined-actions.md
Syntax error in sample code.
Fixes https://github.com/timescale/docs/issues/323
Related: https://github.com/timescale/docs/pull/363
> Remove errant semicolon

- cloud/scaling-a-service.md
Add info about autoscaling on multi-node, and general tidy up of this section.
Fixes https://github.com/timescale/docs-private/issues/22
> Add notes about multi-node autoscale, and general tidy up

- timescaledb/getting-started/access-timescaledb.md
- timescaledb/getting-started/add-data.md
- timescaledb/getting-started/compress-data.md
- timescaledb/getting-started/create-cagg.md
- timescaledb/getting-started/create-hypertable.md
- timescaledb/getting-started/data-retention.md
- timescaledb/getting-started/index.md
- timescaledb/getting-started/launch-timescaledb.md
- timescaledb/getting-started/next-steps.md
- timescaledb/getting-started/query-data.md
> Copy edit Getting Started guide

- timescaledb/overview/faq/faq-postgres.md
- timescaledb/overview/faq/faq-products.md
- timescaledb/overview/faq/faq-using-timescaledb.md
> Copy edit FAQs

- .github/styles/Google/WordList.yml
> update linter to remove Google Cloud and ingest suggestions

- timescaledb/overview/release-notes/changes-in-timescaledb-2.md
I am far too trigger-happy with commits today
> Fix more Vale errors

- .github/styles/Google/Headings.yml
- .github/styles/Google/MarkdownLinks.yml
- .github/styles/Google/Please.yml
- .github/styles/Google/WordList.yml
- Prevent some overenthusiastic heading-capitalization warnings
- Add rule to remove 'please' from docs
- Check for broken Markdown reference-style links
> Add linting rules

- install/installation-windows.md
Update link to Windows download to latest version
Fixes https://github.com/timescale/docs/issues/724
> Update windows version from 2.5.0 to 2.5.1

- timescaledb/how-to-guides/migrate-data/index.md
The whole migrate data section needs a lot of love, but adding this admon for now to resolve the issue.
Fixes https://github.com/timescale/docs/issues/654
> Add admonition about disk space for migrations

- install/installation-cloud-image.md
Updated AMI ids for 2.5.2 release
> Update AMI ids

- api/move_chunk.md
- timescaledb/how-to-guides/data-tiering/index.md
- timescaledb/how-to-guides/data-tiering/move-data.md
While adding the admonition about requiring superuser, I decided this whole section needed a little more ❤️ 
Fixes https://github.com/timescale/docs/issues/749
> Move chunks edits

- timescaledb/overview/faq/faq-postgres.md
> Fix links to PostgreSQL blog posts

- timescaledb/overview/release-notes/index.md
> Release notes 2.5.2

- cloud/disk-management.md
- cloud/memory-management.md
- cloud/page-index/page-index.js
- cloud/scaling-a-service.md
Adds info about OOM killer. In a new PR, since original was in old naming scheme.
- Fixes https://github.com/timescale/docs/issues/358
- Replaces https://github.com/timescale/docs/pull/439
> Add OOM killer info

- install/installation-ubuntu-ami.md
> Update AMI ids for 2.6.0

- install/installation-ubuntu-ami.md
Correct name of base image for our AMI
> Correct name of base image for our AMI

- promscale/distributed-tracing.md
missing tabs - added to fix markdown.
> add tabs to unblock production

- timescaledb/overview/release-notes/index.md
> TimescaleDB 2.6 release notes

- api/add_compression_policy.md
- api/alter_materialized_view.md
- api/continuous_aggregates.md
- api/remove_compression_policy.md
- timescaledb/how-to-guides/continuous-aggregates/compression-on-continuous-aggregates.md
- timescaledb/how-to-guides/continuous-aggregates/index.md
- timescaledb/how-to-guides/continuous-aggregates/troubleshooting.md
> Revert "Revert "Doc updates for compression  on continuous aggregate feature""

- mst/migrate-to-cloud.md
- timescaledb/how-to-guides/migrate-data/index.md
> Fix broken links to Cloud migration guide

- install/installation-windows.md
- install/installation-windows/index.md
- install/installation-windows/windows-releases.md
- install/page-index/page-index.js
- Make latest release links evergreen
- Add links for PG12 and PG13
Fixes #725
> Update Windows release links

- timescaledb/overview/release-notes/index.md
Adds signup link to release notes
> add sign up link to release notes

- timescaledb/how-to-guides/multinode-timescaledb/index.md
Remove MST from the multi-node deployment options 
Partial: https://github.com/timescale/docs-private/issues/19
> Remove MST from the multi-node deployment options

- timescaledb/how-to-guides/multinode-timescaledb/about-multinode.md
Removing MST from the list of multi-node deployment options
Partial: https://github.com/timescale/docs-private/issues/19
> Removing MST from the list of multi-node deployment options

- README.md
Fix Vale errors in `README.md`, one of these is currently blocking merge on other PRs
> Fix Vale errors to unblock merge

- promscale/installation/index.md
- promscale/installation/kubernetes.md
- promscale/installation/tobs.md
Fix Promscale helm/k8s install flow as per discussion with @ramonguiu 
> Fix Promscale installation

- promscale/installation/kubernetes.md
There was a build error that's hard to detect here ATM. Fixing that.
> Fix tag error in callout highlight.

- cloud/migrate-to-cloud/entire-database.md
- cloud/migrate-to-cloud/schema-then-data.md
Add description of skippable warnings for ANALYZE step
Changes on both migration methods
Put old list of warnings in numbered list to better separate the two sections
Fixes #848
> Add ANALYZE troubleshooting

- api/duration_in.md
- api/freq_agg.md
- api/frequency-analysis.md
- api/topn.md
- api/values-freq_agg.md
Previous PR had broken links but hard to see because of a broken build.
- [ x] Latest (Default)
Fixes #876
> Fixing links in preview hyperfunctions PR

- promscale/cli.md
Fix linting errors committed to `latest` that are blocking merge in other PRs.
> Fix linting errors that are blocking merge

- mst/mst-multi-node.md
Adds the deprecation notice in a warning admonition for now, until we have a mechanism for a banner.
Fixes https://github.com/timescale/docs-private/issues/19
> Adds deprecation notice

- timescaledb/how-to-guides/page-index/page-index.js
- timescaledb/how-to-guides/update-timescaledb/downgrade-timescaledb.md
- timescaledb/how-to-guides/update-timescaledb/index.md
Add information on support for downgrading.
Also includes:
- Rewrite of upgrading guide for conventions and clarity
Fixes #809
> Add information on downgrading TimescaleDB

- timescaledb/how-to-guides/update-timescaledb/index.md
Fix typo in code block
Fixes #890
> Fix code typo

- promscale/index.md
Fixed a typo and minor copy edits
Fixes https://github.com/timescale/docs/issues/843
> [Update] Minor edits to Promscale index

- install/installation-macos.md
- timescaledb/how-to-guides/connecting/psql.md
This PR has instructions to install and update timescaledb and postgresql using MacPorts
Fixes https://github.com/timescale/docs/issues/757
> [Update] Installation and Update content to include MacPorts method

- timescaledb/how-to-guides/update-timescaledb/update-timescaledb-2.md
Update code examples to:
- Fix syntax that was giving an error
- Remove smart quotes
Fixes #893
> Fix code examples for guide to updating to TimescaleDB 2.x

- .github/workflows/pr-creation.yml
Update pr comment to guide internal reviewers and give context to build process.
> update pr comment

- cloud/backup-restore-cloud.md
Additional Cloud backup content
Fixes https://github.com/timescale/docs-private/issues/17
> Add Cloud backup content

- promscale/page-index/page-index.js
> Add missing bracket to Promscale page-index

- timescaledb/overview/release-notes/index.md
> Reference CVE ID

- timescaledb/tutorials/financial-candlestick-tick-data/design-tick-schema.md
Twelve Data provides the sample data for the tutorial.
> Mention Twelve Data in the candlestick tutorial

- api/counter_agg_point.md
Broken link to irate page
Fixes https://github.com/timescale/docs/issues/973
> [update] counter_agg()

- promscale/installation/recomm-guide.md
Resource recommendation guide for Promscale traces. 
Fixes https://github.com/timescale/o11y-team-applications/issues/153
> Resource recommendation guide for Promscale traces

- promscale/send-data/prometheus.md
> Update Prometheus config

- timescaledb/how-to-guides/replication-and-ha/index.md
@loquacity Not sure where to point people for configure ha.
> fix 404s on how to guide / high availability

- promscale/manage-data/delete-data.md
- promscale/manage-data/downsampling.md
- promscale/manage-data/index.md
- promscale/manage-data/retention.md
When the docs for trace retention and deletion were added there were added we introduced some confusion that I've resolved by reorganizing the content.
Also made some smaller changes to metric deletion so it's clearer.
> Fix manage data for traces

- cloud/service-settings/customize-configuration.md
Added a note that states the settings vary for each tier.
Fixes https://github.com/timescale/docs/issues/1044
> [update] Modify basic parameters

- timescaledb/tutorials/grafana/visualizations/histograms.md
- timescaledb/tutorials/grafana/visualizations/index.md
- timescaledb/tutorials/page-index/page-index.js
- Add Grafana Visualizations folder
- Add Grafana Visualizations index.md
- Updated page-index.js
- Add Grafana Histograms documentation
> Add Grafana visualizations folder and histograms doc

- promscale/installation/recomm-guide.md
Creating this in favor to #1084 
> Update resource recommendation guide

- promscale/alerts-dashboards-runbooks.md
- promscale/monitoring-promscale.md
- promscale/page-index/page-index.js
Creating this in favor to #1082 
> Monitoring Promscale

- promscale/alert.md
- promscale/downsample-data/index.md
- promscale/visualize-data/apm-experience.md
Fixing links that use () instead of []
> fix invalid links in two Promscale pages

- promscale/monitor.md
> fix spelling mistake

- promscale/alert.md
- promscale/downsample-data/recording.md
- promscale/visualize-data/apm-experience.md
- promscale/visualize-data/grafana.md
- promscale/visualize-data/index.md
made fixes to the links and procedure tags.
> [Update] Promscale link fixes

- api/recompress_chunk.md
- cloud/services/create-a-service-demo.md
- cloud/services/create-a-service.md
- install/installation-cloud-image.md
- install/installation-cloud.md
- install/installation-debian.md
- install/installation-docker.md
- install/installation-macos.md
- install/installation-mst.md
- install/installation-source.md
- install/installation-windows/index.md
- install/managed-service-for-timescaledb.md
- promscale/query-data.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-setup.md
- timescaledb/how-to-guides/replication-and-ha/about-ha.md
- timescaledb/tutorials/financial-candlestick-tick-data/advanced-data-management.md
Fixed broken links (line 4 through 14) in https://docs.google.com/spreadsheets/d/15IbWGV7B9kzr2c5k4COYt-D3ErnI7sMUrSx4Jr1KWm0/edit#gid=1466689422
> [update] Fixed broken-links

- promscale/send-data/opentelemetry.md
Updated the Prometheus remote write endpoint based on the discussion in slack:
https://timescaledb.slack.com/archives/C011FC0PPC5/p1652448729076469
> [update] Prometheus remotewrite endpoint

- api/tdigest.md
- api/uddsketch.md
Was reading through these two pages and noticed the broken links and a typo
> Edits to tdigest and uddsketch

- promscale/manage-data/retention.md
The usage of `NSBP` in a title breaks rendering
> Fix broken title in promscale data retention doc

- timescaledb/how-to-guides/distributed-hypertables/about-distributed-hypertables.md
- timescaledb/overview/limitations.md
Fixed the broken link
Fixes https://github.com/timescale/docs/issues/1130
> [update] Limitations

- timescaledb/how-to-guides/data-retention/create-a-retention-policy.md
Link is broken here: https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/create-a-retention-policy/#see-scheduled-data-retention-jobs
> Fix broken link to timescaledb_information.jobs informational view

- promscale/scale-ha/prometheus-multi-tenancy.md
Documenting a current limitation of Promscale's Prometheus multi-tenancy capability
It documents this issue that is in our backlog: https://github.com/timescale/promscale/issues/1194
> Document current limitation of multi-tenancy

- timescaledb/tutorials/grafana/visualizations/histograms.md
This commit adds:
- small formatting fixes (capitalized SQL keywords & line breaks)
- embedded YouTube video
> Add embedded YouTube video to histogram docs

- promscale/manage-data/delete-data.md
Fixed the typos reported in [slack](https://timescaledb.slack.com/archives/C011FC0PPC5/p1654968555420069)
> [Update] Delete data in Promscale

- timescaledb/how-to-guides/schema-management/index.md
Fixed the broken links reported in [slack](https://timescaledb.slack.com/archives/C63MYDZ35/p1655316396120229)
> [Update] How to (Schema management)

- timescaledb/tutorials/grafana/visualizations/candlestick.md
- Update candlestick tutorial with youtube video link
> update candlestick tutorial with video link

- timescaledb/how-to-guides/data-retention/about-data-retention.md
Fix typo on About data retention page
https://github.com/timescale/docs/issues/1221
> fix: typo in about-data-retention.md

- promscale/backup-restore.md
Added steps to backup for larger databases with custom format and pg_restore for custom format.
Fixes https://github.com/timescale/docs/issues/1188
> Backup and Restore Promscale

- timescaledb/overview/release-notes/index.md
Update the release notes with 2.7.1
> Adding 2.7.1 release notes

- timescaledb/tutorials/grafana/visualizations/time-series.md
This PR adds:
- Embedded video in the time-series Grafana visualization docs
- Cleaned up SQL queries.
> Add embedded video to time-series docs

- timescaledb/tutorials/grafana/visualizations/bar-chart.md
This PR adds:
- Embedded video in the bar chart Grafana visualization docs
- Cleaned up SQL queries.
> Add embedded video to bar chart docs

- timescaledb/overview/release-notes/index.md
> Add 2.7.2 release notes

- timescaledb/overview/release-notes/index.md
> Fix What's new header to not include patch version

- .github/workflows/daily-link-checker.yml
- .github/workflows/link-checker.yml
Reverts timescale/docs#1383
Revert to fix link-checking problem
> Revert "Bump gaurav-nelson/github-action-markdown-link-check from 1 to 1.0.14"

- timescaledb/how-to-guides/alerting.md
Updated the link to Zabbix document that contains information specific to TimescaleDB.
> [update] Alerting

- api/financial-analysis.md
- api/ohlc.md
- api/open-high-low-close-at.md
- api/open-high-low-close.md
- api/page-index/page-index.js
- api/rollup.md
- timescaledb/how-to-guides/hyperfunctions/about-hyperfunctions.md
Add documention for new toolkit OHLC aggregate
>  OHLC Toolkit Experimental docs

- api/asap.md
- api/lttb.md
LTTB and timevector were stabilized in the recent 1.9/1.10.1
toolkit release.  This change updates the documentation
to bring it up to date.
> Update LTTB and ASAP pages

- api/month_normalize.md
The example code for days_in_month() was missing a parentheses
> fixing example code

- timescaledb/how-to-guides/write-data/upsert.md
> Revert "Remove note re: `ON CONFLICT ON CONSTRAINT`"

- api/time_bucket.md
- api/time_bucket_ng.md
- timescaledb/how-to-guides/time-buckets/about-time-buckets.md
> Revert "[TimescaleDB 2.8] Update `time_bucket`"

- api/time_bucket.md
- api/time_bucket_ng.md
- timescaledb/how-to-guides/time-buckets/about-time-buckets.md
> Revert "Revert "[TimescaleDB 2.8] Update `time_bucket`""

- timescaledb/how-to-guides/write-data/upsert.md
> Revert "Revert "Remove note re: `ON CONFLICT ON CONSTRAINT`""

- timescaledb/overview/release-notes/index.md
> Add 2.8.0 release notes

- mst/troubleshooting.md
Add troubleshooting information for connection termination with version mismatch error.
[KB Article](https://kb-managed.timescale.com/en/articles/4000086-connection-dies-while-trying-to-update-timescale-extension)
> [update] MST  Troubleshooting

- .github/workflows/deploy.yml
Update the text used to give the preview link in the PR, to include that ppl should use incognito mode. I'm sick of mentioning it all the time 😉 
> Update action text for PR

- _partials/_cloud-integrations-metrics.mdx
- cloud/integrations.md
> Revert "Revert "Add list of metrics to check in Cloud integrations""

- cloud/page-index/page-index.js
This reverts commit 930ec4d7a12424e2d96b590150385e459b373478.
> Revert "Debug cloud integrations page"

- api/asap.md
In toolkit 1.11.0 ASAP is no longer an experimental function.  This updates the document to reflect that.
> Remove experimental flag from ASAP

- timescaledb/overview/how-does-it-compare/timescaledb-vs-postgres.md
After completing our newest benchmark, our comparison of relative advantages and disadvantages for TimescaleDB and PostgreSQL has changed.
[Benchmark](https://www.timescale.com/blog/postgresql-timescaledb-1000x-faster-queries-90-data-compression-and-much-more/)
Fixes https://github.com/timescale/timescale-marketing/issues/295
> Update TimescaleDB and PostgreSQL comparison

- promscale/backup-restore.md
The order of post-restore calls matters starting from ts 2.8.0 (See https://github.com/timescale/promscale_extension/pull/500)
> The order of post-restore calls matters starting from ts 2.8.0

- timescaledb/overview/release-notes/index.md
Update the release notes with the 2.8.1 changelog
> Added the version 2.8.1 changelog

- timescaledb/how-to-guides/hypertables/create.md
- timescaledb/tutorials/grafana/grafana-timescalecloud.md
Fixes https://github.com/timescale/docs/issues/1684
and a typo about Grafana on MST
> added a crossref and fixed a typo

- promscale/send-data/index.md
We can send data from Jaeger directly now
> We can send data from Jaeger directly now

- mst/failover.md
Added the failover details from [this article](https://app.intercom.com/a/apps/uvcadzno/articles/articles/2755200/show)
> [new] MST failover

- api/month_normalize.md
Updates the tag type in month_normalize to correctly use Toolkit's Experimental tag
> fix tag type for month normalize

- api/counter_agg_point.md
> Correcting counter_agg argument type typo

- install/installation-debian.md
Remove ubuntu versions we no longer build packages for
> Remove ubuntu versions we no longer build packages for

- promscale/tobs/tobs.md
Link to cert manager results in 404
Fixes https://github.com/timescale/docs/issues/1731
> [update] Install Tobs

- install/installation-debian.md
Installation guide have some commands to run shell with `sudo`. It is not a good practice. This PR is to replace with safer commands.
> Don't run shell under root

- api/_hyperfunctions/stats_agg-one-variable/kurtosis.md
- api/_hyperfunctions/stats_agg-one-variable/num_vals.md
- api/_hyperfunctions/stats_agg-one-variable/skewness.md
- api/_hyperfunctions/stats_agg-one-variable/stddev.md
- api/_hyperfunctions/stats_agg-one-variable/variance.md
- api/_hyperfunctions/stats_agg-two-variables/kurtosis_y_x.md
- api/_hyperfunctions/stats_agg-two-variables/num_vals.md
- api/_hyperfunctions/stats_agg-two-variables/skewness_y_x.md
- api/_hyperfunctions/stats_agg-two-variables/stats_agg.md
- api/_hyperfunctions/stats_agg-two-variables/stddev_y_x.md
- api/_hyperfunctions/stats_agg-two-variables/variance_y_x.md
Formatting for code examples was wrong on some `stats_agg` files, so the example descriptions were not showing up on the site.
> fix(stats_agg): fix formatting

- promscale/installation/kubernetes.md
Updated the link to Promscale values.yaml
Fixes https://github.com/timescale/docs/issues/1789
> [update] Install Promscale on Kubernetes

- promscale/index.md
- promscale/installation/index.md
Help users discover they can get started more easily with Promscale by using Timescale Cloud
> Add call out to promote Timescale Cloud

- api/_hyperfunctions/stats_agg-two-variables/average_y_x.md
Signed-off-by: jerryxwu <jerry@timescale.com>
> Correct a typo in average_y_x.md

- timescaledb/how-to-guides/ingest-data/ingest-parallel-copy.md
- timescaledb/how-to-guides/ingest-data/ingest-telegraf.md
- timescaledb/how-to-guides/page-index/page-index.js
- Updated the how-to to ingest data using telegraf
- Updated the index page to install and use timescaledb-parallel-copy
PS: Reviewers after this how to is merged may be we can remove Telegraf from the tutorials. With redirects to the new how-to
> [update] Added telegraf to how-to

- api/.templates/hyperfunctions/README.MD
- api/.templates/hyperfunctions/accessor.md
- api/.templates/hyperfunctions/aggregate.md
- api/.templates/hyperfunctions/examples.md
- api/.templates/hyperfunctions/intro.md
- api/.templates/hyperfunctions/rollup.md
Add templates so it's easier to fill out new hyperfunction groups with the new organization.
> chore: add hyperfunctions templates

- promscale/send-data/prometheus.md
Remove description of parameters no longer used
> Remove description of parameters no longer used

- timescaledb/overview/release-notes/index.md
> 2.9.1 Release notes

- api/alter_data_node.md
- api/page-index/page-index.js
- timescaledb/how-to-guides/multinode-timescaledb/multinode-ha.md
- timescaledb/timescaledb-edition-comparison.md
Add documentation for alter_data_node 
> Add documentation for alter_data_node

- timescaledb/tutorials/aws-lambda/create-data-api.md
update the name of the directory after validating the content in the [blog](https://www.timescale.com/blog/aws-lambda-for-beginners-overcoming-the-most-common-challenges/)
Fixes https://github.com/timescale/docs/issues/1842)
> [update] Create a data API for TimescaleDB

- install/installation-source.md
- install/installation-windows.md
Getting some build errors on the preview, hoping this fixes it.
> remove highlight block

- api/job_errors.md
- api/page-index/page-index.js
Add documentation page for troubleshooting view for job errors.
Fixes #1817
> Add page for job_errors view

- api/decompress_chunk.md
Merged a change this morning that broke the site build. This should fix it.
> angle brackets were breaking the site build

- timescaledb/overview/release-notes/index.md
Update the release notes with the 2.9.2 changelog.
> Added the version 2.9.2 changelog

- api/_hyperfunctions/timeline_agg/timeline_agg.md
> Fix broken link

- timescaledb/quick-start/dotnet.md
Updated the method GetDateTime.
Validated against: https://www.npgsql.org/doc/api/Npgsql.NpgsqlDataReader.html#Npgsql_NpgsqlDataReader_GetDateTime_System_Int32_
Fixes https://github.com/timescale/docs/issues/1990
> [update] Quick Start: .NET and TimescaleDB

- install/installation-linux.md
revert the version of PostgreSQL in install because 15 is not GA yet.
> [update] Install on Ubuntu

- timescaledb/overview/release-notes/index.md
Update the release notes with the 2.9.3 changelog.
> Added the version 2.9.3 changelog

- .github/styles/Google/WordList.yml
- .github/styles/Vocab/Timescale/accept.txt
- cloud/migrate-to-cloud/hypermigrate.md
- cloud/migrate-to-cloud/hypershift.md
- cloud/migrate-to-cloud/index.md
- cloud/page-index/page-index.js
This adds documentation for the ~hypermigrate~ hypershift feature
Fixes https://github.com/timescale/docs-private/issues/60
> Hypershift docs

- cloud/migrate-to-cloud/hypershift.md
Removed as per @VineethReddy02 
> Remove experimental admon

- cloud/service-operations/maintenance.md
Added PG15 support to the major version upgrades docs
> Update maintenance to include pg15

- getting-started/index.md
- promscale/quick-start.md
- promscale/recommendations/config-recomm.md
- promscale/recommendations/resource-recomm.md
- promscale/send-data/remote-write.md
- use-timescale/configuration/advanced-parameters.md
- use-timescale/configuration/customize-configuration.md
- use-timescale/vpc.md
Related to https://github.com/timescale/docs-private/issues/76
> clean up incorrect 'product' keys that slipped through

- page-index/page-index.js
Adds Promscale back to the main nav. Promscale migration will now occur in Phase 2.
Partial: https://github.com/timescale/docs-private/issues/70
> Add back Promscale

- timescaledb/overview/release-notes/index.md
> Add release notes for 2.10.1

- use-timescale/connecting/about-connecting.md
- use-timescale/connecting/about-psql.md
- use-timescale/connecting/azure-data-studio.md
- use-timescale/connecting/dbeaver.md
- use-timescale/connecting/index.md
- use-timescale/connecting/pgadmin.md
- use-timescale/connecting/psql.md
Partial https://github.com/timescale/docs-private/issues/77
> Cloud-centric edits - Use Timescale → Connecting

- navigation/page-index/page-index.js
Related to https://github.com/timescale/docs-private/issues/64
> nav: point search link to pre-filled query for "timescale"

- self-hosted/configuration/about-configuration.md
- self-hosted/configuration/configuration.md
- self-hosted/configuration/docker-config.md
- self-hosted/configuration/index.md
- self-hosted/configuration/postgres-config.md
- self-hosted/configuration/telemetry.md
- self-hosted/configuration/timescaledb-config.md
- self-hosted/configuration/timescaledb-tune.md
Light edits to self-hosted Configuration pages
> [Update] Self-hosted Configuration pages

- api/_hyperfunctions/time_weight/interpolated_average.md
> Stabilizing interpolated average

- self-hosted/backup-and-restore/docker-and-wale.md
- self-hosted/backup-and-restore/index.md
- self-hosted/backup-and-restore/pg-dump-and-restore.md
- self-hosted/backup-and-restore/physical.md
Edited self-hosted backup and restore pages for cloud-centric updates
> [Cloud-centric] Self-hosted backup and restore

- cloud/service-operations/service-management.md
- timescaledb/how-to-guides/multinode-timescaledb/multinode-config.md
- Checked on Timescale cloud that it is indeed the Service management section
- Minor typo fix
Fixes https://github.com/timescale/docs/issues/2140 and https://github.com/timescale/docs/issues/2133
> [Update] TimescaleDB services and Multinode

- _code-samples/toolkit/two-step_aggregation.md
- about/release-notes/index.md
- api/_hyperfunctions/time_bucket_gapfill/intro.md
- api/create_hypertable.md
- mlc_config.json
- mst/installation-mst.md
- self-hosted/install/index.md
- self-hosted/upgrades/upgrade-docker.md
- tutorials/aws-lambda/index.md
- tutorials/custom-timescaledb-dashboards.md
- tutorials/grafana/visualizations/bar-chart.md
- tutorials/grafana/visualizations/time-series.md
- use-timescale/limitations.md
- use-timescale/vpc.md
> fix(links): broken links from reorg, batch 4

- use-timescale/compression/about-compression.md
- use-timescale/compression/decompress-chunks.md
- use-timescale/compression/index.md
- use-timescale/compression/manually-compress-chunks.md
- use-timescale/compression/modify-a-schema.md
- use-timescale/configuration/about-configuration.md
- use-timescale/configuration/customize-configuration.md
- use-timescale/continuous-aggregates/about-continuous-aggregates.md
- use-timescale/continuous-aggregates/create-a-continuous-aggregate.md
- use-timescale/continuous-aggregates/create-index.md
- use-timescale/continuous-aggregates/drop-data.md
- use-timescale/continuous-aggregates/hierarchical-continuous-aggregates.md
- use-timescale/continuous-aggregates/index.md
- use-timescale/continuous-aggregates/materialized-hypertables.md
- use-timescale/continuous-aggregates/migrate.md
- use-timescale/continuous-aggregates/real-time-aggregates.md
- use-timescale/continuous-aggregates/refresh-policies.md
- use-timescale/data-retention/about-data-retention.md
- use-timescale/data-retention/create-a-retention-policy.md
- use-timescale/data-retention/data-retention-with-continuous-aggregates.md
- use-timescale/data-retention/manually-drop-chunks.md
- use-timescale/schema-management/about-indexing.md
- use-timescale/schema-management/about-schemas.md
- use-timescale/schema-management/indexing.md
- use-timescale/schema-management/manage-storage.md
- use-timescale/schema-management/triggers.md
Light edits
-  The "materialised engine" had two paragraphs with the same title. So moved it under one 
- added about to configuration for Timescale Cloud
> [cloud-centric] Use-timescale (continuous aggregates, schema management, data retention, compression, configuration)

- cloud/page-index/page-index.js
- cloud/service-operations/high-availability.md
- cloud/service-operations/read-scaling.md
- cloud/service-operations/replicas.md
Adds the read replicas docs (launching on Monday), and updates the HA replicas docs to use the new tab names that will change post-launch.
> Create read replicas docs

- cloud/postgresql-extensions.md
> Add pgpcre, remove query

- _troubleshooting/self-hosted/pg_dump-permission-denied.md
Added the error message, cause, and workaround for the error when using pg_dump on self-hosted.
Fixes https://github.com/timescale/docs/issues/2226
*   [ ] Does the content contain clear sections for concepts, tasks, …
> [update] Troubleshooting section with the pg_dump error

- api/_hyperfunctions/uddsketch/approx_percentile_array.md
> Remove experimental flag from approx percentile array

- api/_hyperfunctions/freq_agg/examples.md
- api/_hyperfunctions/freq_agg/into_values.md
- api/_hyperfunctions/freq_agg/intro.md
- api/_hyperfunctions/freq_agg/max_frequency.md
- api/_hyperfunctions/freq_agg/mcv_agg.md
- api/_hyperfunctions/freq_agg/min_frequency.md
- api/_hyperfunctions/freq_agg/rollup.md
- api/_hyperfunctions/freq_agg/topn.md
In toolkit 1.16.0, `topn_agg` was renamed `mcv_agg` and stabilized.  All of the accessors for this aggregate were also stabilized.  The only remaining experimental API in this family is `freq_agg`.
*   [ ] Is the content free …
> Update frequency docs for toolkit 1.16.0

- .data/redirects.js
@Rajakavitha1 picked up a typo in https://github.com/timescale/docs/pull/2282 but it auto-merged, so this is the fast followup fix 
*   [ ] Does the content contain clear sections for …
> Remove extra slash

- mst/integrations/metrics-datadog.md
- use-timescale/hypertables/create.md
- removed the steps to create an API in Datadog from our docs and provided a link to the Datadog docs
- validated and updated the integrations section with the latest UI
- fixed one bad link for migration https://github.com/timescale/docs/issues/2306
Fixes https://github.com/timescale/docs/issues/2067 …
> [Update] MST Datadog integrations

- use-timescale/postgresql-extensions.md
Added a new extension to Cloud
*   [x] Is the content technically accurate?
*   [x] Is the content complete?
*   [x] Is the content presented in a logical order?
*   [x] Does the content use appropriate names for features and products?
*   [x] Does the content provide relevant links to further information?
*   [ ] Have any images been uploaded to the correct location, and …
> add pgvector to available extensions list

- use-timescale/postgresql-extensions.md
added pl/pgsql to our list as it was missing
*   [x] Is the content technically accurate?
*   [x] Is the content complete?
*   [x] Is the content presented in a logical order?
*   [x] Does the content use appropriate names for features and products?
*   [x] Does the content provide relevant links to further information? …
> add entry to extensions table

- api/alter_job.md
> Document next_start calculation on job failure

- use-timescale/services/index.md
Mention using Timescale Terraform provider to manage services.
Fixes https://github.com/timescale/docs-private/issues/83
*   [ ] Have …
> [update] Use Timescale services

- self-hosted/install/installation-cloud-image.md
Fixes typo 'datase' inside `self-hosted/install/installation-cloud-image.md`
*   [ ] Have any …
> fix(typo) - datase

- self-hosted/compression/manual-compression.md
Fix inaccurate documentation regarding compressed chunk roll up.
*   [ ] Have any images been …
> Fix roll up compression example in manual-compression.md

- about/release-notes/index.md
Add changelog for Timescaledb 2.11.0  …
> Add 2.11.0 changelog

- quick-start/ruby.md
Updated the code win step 6 to connect to TimescaleDB
Fixes https://github.com/timescale/docs/issues/2393
*   [ ] Have any images been …
> update the code

- mst/migrate-to-mst.md
Fix minor formatting issue on Migrate to MST docs page.
N/A
*   [ ] Have any images been uploaded to the correct location, and are …
> Fix formatting in migrate-to-mst.md

- use-timescale/data-tiering/about-data-tiering.md
Rephrased the Latency Limitations
*   [ ] Have any images been uploaded to the correct location, …
> [update] Data tiering

- .data/redirects.js
> fix: resync redirects with cloudflare

- _partials/_early_access.md
Remove mention on early access features being production ready.
Relevant information can be found on the following slack threads:
- https://iobeam.slack.com/archives/C032DCNQ1M1/p1686842557178319?thread_ts=1686841517.434709&cid=C032DCNQ1M1
- https://iobeam.slack.com/archives/C01CBSBA0C9/p1686082602752569?thread_ts=1685737994.884109&cid=C01CBSBA0C9
*   [ ] Does the content use plain …
> Remove mention on early access features being production ready

- tutorials/blockchain-analyze/index.md
- tutorials/blockchain-query/index.md
- tutorials/energy-data/dataset-energy.md
- tutorials/energy-data/index.md
- tutorials/financial-tick-data/index.md
- tutorials/nyc-taxi-cab/index.md
- tutorials/nyc-taxi-geospatial/index.md
Fixes https://github.com/timescale/docs/issues/2499 and https://github.com/timescale/docs/issues/2500
*   [ ] Does the content contain clear sections for concepts, tasks, and …
> [update] Tutorials wordings

- use-timescale/integrations/observability-alerting/grafana/index.md
- use-timescale/page-index/page-index.js
Update the links
Fixes https://github.com/timescale/docs/issues/2507
*   [ ] Have any images been uploaded to the correct location, …
> [update] integration grafana

- _troubleshooting/cloud-jdbc-authentication-support.md
Fix 403 for integrations TS
Fixes https://github.com/timescale/docs/issues/2503 …
> [update] Integrations

- self-hosted/install/installation-kubernetes.md
Added the link to the guide in the GitHub repo.
*   [ ] Have any images been uploaded to the …
> [update] Kubernetes Installation 

- _partials/_cloud-create-connect-tutorials.md
- tutorials/blockchain-analyze/blockchain-dataset.md
- tutorials/blockchain-analyze/index.md
- tutorials/blockchain-query/blockchain-dataset.md
- tutorials/blockchain-query/index.md
- tutorials/energy-data/dataset-energy.md
- tutorials/energy-data/index.md
- tutorials/financial-ingest-real-time/financial-ingest-dataset.md
- tutorials/financial-ingest-real-time/financial-ingest-query.md
- tutorials/financial-ingest-real-time/index.md
- tutorials/financial-tick-data/financial-tick-dataset.md
- tutorials/financial-tick-data/index.md
- tutorials/ingest-real-time-websocket-data.md
- tutorials/nyc-taxi-cab/dataset-nyc.md
- tutorials/nyc-taxi-cab/index.md
- tutorials/nyc-taxi-geospatial/dataset-nyc.md
- tutorials/nyc-taxi-geospatial/index.md
- tutorials/page-index/page-index.js
- use-timescale/compression/about-compression.md
Avoid the repeated sign-up or sign-in details in the tutorials
Made all collapsible by default
Fixes https://github.com/timescale/docs-private/issues/144 …
> [Update] Tutorials

- tutorials/financial-ingest-real-time/financial-ingest-query.md
Remove the redundant paragraph in the introduction of Query page.
*   [ ] Have any images been …
> [update] Financial Part 2 tutorials

- self-hosted/install/installation-source.md
Changed the git checkout instruction to the most recent release tag. I double checked the source code to confirm the tag was available.
Fixes the reference to the most recent release tag on https://docs.timescale.com/self-hosted/latest/install/installation-source/
*   [ ] Is the content free from …
> Update most recent release tag

- tutorials/financial-ingest-real-time/financial-ingest-dataset.md
- tutorials/financial-ingest-real-time/financial-ingest-query.md
- tutorials/financial-ingest-real-time/index.md
- tutorials/nyc-taxi-geospatial/dataset-nyc.md
- tutorials/nyc-taxi-geospatial/plot-nyc.md
The Finance Part 2 and Transport Part 2 tutorials had bad navigation elements. This PR fixes the metadata to resolve the problems.
*   [ ] Does the content contain clear sections for …
> Fix tutorial navigation

- use-timescale/account-management.md
Updated the screenshots 
Fixes https://github.com/timescale/docs-private/issues/126
*   [ ] Have any images been uploaded to the …
> [update] Account management and Billing screenshots

- api/job_errors.md
> Fix command for updating job errors retention job config

- getting-started/tables-hypertables.md
- getting-started/time-series-data.md
Fixes https://github.com/timescale/docs/issues/2593
*   [ ] Have any images been uploaded …
> [update] Tables and hypertables

- use-timescale/backup-restore-cloud.md
Add additional information that needs to be provided when raising a support ticket
Fixes https://github.com/timescale/docs/issues/2578 …
> [update] Backup and restore in cloud

- self-hosted/upgrades/major-upgrade.md
- self-hosted/upgrades/minor-upgrade.md
Tested and validated the major and minor upgrades in Docker
Provided the link to the docker section of the document in minor and major upgrade section of the guides.
Fixes: https://github.com/timescale/docs/issues/2574 …
> [Update] Minor upgrades and Major upgrades

- self-hosted/install/index.md
Added a link to the release notes section so that the users are aware of the latest release numbers.
Fixes https://github.com/timescale/docs/issues/1965 …
> [update] Install TimescaleDB - self hosted

- use-timescale/metrics-logging/integrations.md
- use-timescale/metrics-logging/service-logs.md
- use-timescale/metrics-logging/service-metrics.md
- use-timescale/services/service-explorer.md
updated the screenshots
Fixes https://github.com/timescale/docs-private/issues/126
@Loquacity  and @gina-alioto  with this we are at 93.75 percent done.  …
> [update] Screenshots for services, metrics, and integrations

- api/compression.md
URLs were declared incorrectly in the admonition
*   [ ] Have any images been uploaded to the …
> fix URLs in admonition

- self-hosted/replication-and-ha/configure-replication.md
Fix the broken link. updated the link to the new location: https://hub.docker.com/_/postgres/
Fixes https://github.com/timescale/docs/issues/2645
*   [ ] Does the content contain clear sections for concepts, tasks, and …
> update the link for docker hub

- about/timescaledb-editions.md
- Clarify Apache 2 name 
- Remove reference to third party hosting sites 
- Fix section headers
* …
> Clarify Apache 2 name, remove reference to third party hosting sites 

- _partials/_usage-based-storage-intro.md
- use-timescale/compression/index.md
Update the link in compression and the warning for compression in cloud
*   [ ] Have any images …
>  [update] Compression

- use-timescale/upgrades.md
- use-timescale/vpc.md
Updated the screenshots
Fixes https://github.com/timescale/docs-private/issues/126
*   [ ] Have any images been uploaded to the …
> [update]Update the screenshots vpc and upgrades

- use-timescale/migration/timescaledb-backfill.md
I'm just adding all the information I think could be important on how to use the backfill tool. 
I'm taking upon the offer of the docs team to just write information and they will find the way to present it in a cohesive manner.
> WIP: pg_dump and pg_restore docs: add backfill tool docs

- use-timescale/migration/dual-write-and-backfill.md
> WIP: pg_dump and pg_restore docs: Postgres source

- use-timescale/continuous-aggregates/time.md
fix missing parenthesis in example
*   [ ] Have any images been uploaded to the correct location, …
> fix: missing parenthesis in example

- use-timescale/migration/dual-write-and-backfill.md
- use-timescale/migration/timescaledb-backfill.md
> Document backfill cascade-up and wip refresh caggs

- migrate/dual-write-and-backfill/dual-write-from-timescaledb.md
> Fix a typo in a command

- migrate/dual-write-and-backfill/timescaledb-backfill.md
> Include continuous aggregates in backfill-tool description

- _partials/_migrate_dual_write_6a_through_c.md
- _partials/_migrate_dual_write_6e_turn_on_compression_policies.md
- _partials/_migrate_dual_write_step2.md
- migrate/dual-write-and-backfill/dual-write-from-other.md
- migrate/dual-write-and-backfill/dual-write-from-postgres.md
- migrate/page-index/page-index.js
This adds documentation for how to do dual-write and backfill from a non-postgresql database to Timescale.
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
and have …
> Add documentation for dual-write from other

- use-timescale/regions.md
> Add us-east-2 and ap-southeast-1 to regions.md

- migrate/dual-write-and-backfill/index.md
> Add link to dual-write from other to dual-write index page

- migrate/dual-write-and-backfill/timescaledb-backfill.md
Document --from flag for timescaledb-backfill …
> Document --from flag for timescaledb-backfill

- use-timescale/metrics-logging/index.md
- use-timescale/metrics-logging/metrics-to-prometheus.md
Fixing nits.
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
* …
> fix ref nits

- self-hosted/configuration/configuration.md
- self-hosted/configuration/timescaledb-config.md
To document `timescaledb.bgw_scheduler_restart_time`
*   [ ] Have any images been uploaded to the correct location, and are …
> Document timescaledb.bgw_scheduler_restart_time

- use-timescale/upgrades.md
Correct the description of the maintenance behavior when replicas are present. In the previous version, we promised our customers no downtime and two failover events, while in reality, the maintenance may result in up to two write downtimes, up to one minute each, since the replica waits for up to a minute for the primary to restart.
See https://iobeam.slack.com/archives/CDZGF8U7J/p1697611316402379
*   [ ] Is the content free …
> Expectations on the maintenance behavior with a replica.

- use-timescale/integrations/config-deploy/index.md
- use-timescale/integrations/config-deploy/terraform.md
- use-timescale/integrations/index.md
- use-timescale/page-index/page-index.js
Add our Terraform to docs so users can find it if they search for it in our docs
> add Terraform to docs

- migrate/index.md
Include live migrations in index/parent page.  …
> Add live migrations to index page

- self-hosted/configuration/configuration.md
- self-hosted/configuration/timescaledb-config.md
This reverts commit 633f3d8fc9e8b0268af771fd6b92efaacefcb9f4.
*   [ ] Does the content contain clear sections for concepts, tasks, and …
> Revert "Document timescaledb.bgw_scheduler_restart_time (#2748)"

- use-timescale/services/connection-pooling.md
Show users how to use the SHOW commands in pgbouncer with our connection poolers
*   [ ] Have any …
> add SHOW commands for monitoring

- about/release-notes/index.md
Update the release notes with the 2.12.2 changelog.
* …
> Added the version 2.12.2 changelog

- use-timescale/backup-restore/index.md
> update index for broken link

- use-timescale/metrics-logging/index.md
- use-timescale/metrics-logging/insights.md
- use-timescale/metrics-logging/service-metrics.md
- use-timescale/page-index/page-index.js
This PR adds a new page within the Insights docs. We moved the docs previously named `Query stats` to a new page called Insights.  
We are releasing new features related to the query stats page, and this PR keeps the docs up to date with the latest features.
*   [x] Is the content technically accurate?
*   [x] Is the content complete?
*   [x] Is the content presented in a logical order?
*   [x] Does the content use appropriate names for features and products?
*   [x] Does the content provide relevant links to further information?
*   [x] Is the content free from typos?
*   [x] Does the content use plain English?
*   [x] Does the content contain clear sections for concepts, tasks, and references?
* …
> Insights docs
